Repository NVIDIA/NeMo-Agent-Toolkit, pull requests merged in 2025-05, with the labels that each got.

#182 Update `AIQChatRequest` to support image and audio input
  src/aiq/data_models/api_server.py
Labels: improvement, non-breaking

#188 Fix hyperlink ins the simple_calculator README
  examples/simple_calculator/README.md
Labels: doc, non-breaking

#170 Add support for fine-grained tracing using W&B Weave
  docs/source/_static/weave_tracing.png
  docs/source/guides/fine-grained-tracing-with-weave.md
  docs/source/guides/index.md
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-weave.yml
  packages/aiqtoolkit_weave/pyproject.toml
  packages/aiqtoolkit_weave/src/aiq/meta/pypi.md
  packages/aiqtoolkit_weave/src/aiq/plugins/weave/__init__.py
  packages/aiqtoolkit_weave/src/aiq/plugins/weave/register.py
  packages/aiqtoolkit_weave/src/aiq/plugins/weave/weave_sdk.py
  pyproject.toml
  src/aiq/observability/async_otel_listener.py
Labels: improvement, non-breaking

#190 Fix typo in CPR detected by co-pilot
  packages/aiqtoolkit_weave/src/aiq/meta/pypi.md
Labels: doc, non-breaking

#163 Note the name change in the top-level documentation and README.md
  README.md
  docs/source/index.md
Labels: doc, non-breaking

#191 fix typo in evaluate documentation for max_concurrency
  docs/source/concepts/evaluate.md
Labels: bug, non-breaking

#195 Fix a typo in the weave README
  docs/source/guides/fine-grained-tracing-with-weave.md
  examples/simple_calculator/README.md
Labels: doc, non-breaking

#198 Config option to specify the intermediate step types in workflow_output.json
  docs/source/concepts/evaluate.md
  src/aiq/data_models/evaluate.py
  src/aiq/eval/dataset_handler/dataset_handler.py
  src/aiq/eval/evaluate.py
  tests/aiq/eval/dataset_handler/test_dataset_handler.py
Labels: improvement, non-breaking

#167 Make `opentelemetry` and `phoenix` as optional dependencies
  docs/source/concepts/observability.md
  examples/agents/rewoo/README.md
  pyproject.toml
  src/aiq/builder/workflow.py
  src/aiq/builder/workflow_builder.py
  src/aiq/cli/type_registry.py
  src/aiq/meta/pypi.md
  src/aiq/observability/async_otel_listener.py
  src/aiq/observability/register.py
  src/aiq/utils/optional_imports.py
  uv.lock
Labels: improvement, non-breaking

#130 Support user-defined HTTP request metadata in workflow tools.
  src/aiq/builder/context.py
  src/aiq/builder/function_base.py
  src/aiq/data_models/api_server.py
  src/aiq/front_ends/fastapi/fastapi_front_end_plugin_worker.py
  src/aiq/runtime/session.py
  src/aiq/runtime/user_metadata.py
  tests/aiq/server/test_unified_api_server.py
Labels: feature request, non-breaking

#209 Check if request is present before setting attributes
  src/aiq/runtime/session.py
Labels: bug, non-breaking

#193 Add the alert triage agent example
  .gitattributes
  ci/vale/styles/config/vocabularies/aiq/accept.txt
  examples/alert_triage_agent/.env_example
  examples/alert_triage_agent/README.md
  examples/alert_triage_agent/configs
  examples/alert_triage_agent/data
  examples/alert_triage_agent/pyproject.toml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/__init__.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/categorizer.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/ata_diagram.png
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/benign_fallback_test_data.json
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/maintenance_static_dataset.csv
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/test_data.csv
  examples/alert_triage_agent/src/aiq_alert_triage_agent/hardware_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/host_performance_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/maintenance_check.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/monitoring_process_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/network_connectivity_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/playbooks.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/prompts.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/register.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/run.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_analysis_agent.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_heartbeat_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_performance_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/utils.py
  pyproject.toml
  uv.lock
Labels: improvement, non-breaking

#208 Fix plugin dependencies
  ci/release/update-version.sh
  ci/release/update_toml_dep.py
  ci/scripts/gitlab/build_wheel.sh
  examples/agno_personal_finance/pyproject.toml
  examples/automated_description_generation/pyproject.toml
  examples/documentation_guides/workflows/text_file_ingest/pyproject.toml
  examples/email_phishing_analyzer/pyproject.toml
  examples/plot_charts/pyproject.toml
  examples/por_to_jiratickets/pyproject.toml
  examples/simple/pyproject.toml
  examples/simple_calculator/pyproject.toml
  examples/swe_bench/pyproject.toml
  packages/aiqtoolkit_agno/pyproject.toml
  packages/aiqtoolkit_crewai/pyproject.toml
  packages/aiqtoolkit_langchain/pyproject.toml
  packages/aiqtoolkit_llama_index/pyproject.toml
  packages/aiqtoolkit_mem0ai/pyproject.toml
  packages/aiqtoolkit_semantic_kernel/pyproject.toml
  packages/aiqtoolkit_test/pyproject.toml
  packages/aiqtoolkit_weave/pyproject.toml
  packages/aiqtoolkit_zep_cloud/pyproject.toml
  packages/compat/agentiq/pyproject.toml
  packages/compat/agentiq_agno/pyproject.toml
  packages/compat/agentiq_crewai/pyproject.toml
  packages/compat/agentiq_langchain/pyproject.toml
  packages/compat/agentiq_mem0ai/pyproject.toml
  packages/compat/agentiq_test/pyproject.toml
  pyproject.toml
  uv.lock
Labels: bug, non-breaking

#210 Regenerate `uv.lock`, cleaned up `pyproject.toml` for profiler agent example and fixed broken link in `README`
  examples/profiler_agent/README.md
  examples/profiler_agent/pyproject.toml
  packages/aiqtoolkit_weave/pyproject.toml
  uv.lock
Labels: improvement, non-breaking

#186 Removed `disable=unused-argument` from pylint checks
  pyproject.toml
Labels: improvement, non-breaking

#215 Exception handling for discovery_metadata.py
  src/aiq/data_models/discovery_metadata.py
Labels: improvement, non-breaking

#217 Treat a tagged commit the same as a nightly build
  .gitlab-ci.yml
  ci/release/update-version.sh
  ci/scripts/gitlab/artifactory_upload.sh
  ci/scripts/gitlab/build_wheel.sh
  ci/scripts/gitlab/common.sh
Labels: bug, non-breaking

#221 Add a CLI command to list all tools available via the MCP server
  docs/source/components/mcp.md
  docs/source/guides/mcp-server.md
  examples/simple_calculator/README.md
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-mcp-date.yml
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-mcp-math.yml
  src/aiq/cli/commands/info/info.py
  src/aiq/cli/commands/info/list_mcp.py
  tests/aiq/cli/commands/info/test_list_mcp.py
Labels: improvement, non-breaking

#225 For remote evaluation, workflow config is not needed
  docs/source/guides/evaluate-api.md
  examples/simple/src/aiq_simple/configs/eval_only_config.yml
  src/aiq/builder/eval_builder.py
  src/aiq/builder/workflow_builder.py
Labels: improvement, non-breaking

#222 Move configurable parameters from env vars to config file
  examples/alert_triage_agent/.env_example
  examples/alert_triage_agent/README.md
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_live_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_test_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/hardware_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/host_performance_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/maintenance_check.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/monitoring_process_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/network_connectivity_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/register.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_heartbeat_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_performance_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/utils.py
Labels: improvement, non-breaking

#227 Fix vulnerabilities in the alert triage agent example
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_test_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/hardware_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/run.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_heartbeat_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_performance_check_tool.py
Labels: improvement, non-breaking

#226 Add e2e test for the alert triage agent
  examples/alert_triage_agent/tests/test_alert_triage_agent_workflow.py
Labels: improvement, non-breaking

#229 Fix remaining nSpect vulnerabilities for `1.1.0`
  examples/alert_triage_agent/src/aiq_alert_triage_agent/run.py
  src/aiq/tool/code_execution/local_sandbox/local_sandbox_server.py
Labels: improvement, non-breaking

#231 Remove redundant span stack handling and error logging
  src/aiq/observability/async_otel_listener.py
Labels: bug, non-breaking

#244 Bugfix for alert triage agent to run in python 3.11
  examples/alert_triage_agent/src/aiq_alert_triage_agent/categorizer.py
Labels: bug, non-breaking

#245 Fix multiple documentation and logging bugs for `v1.1.0-rc3`
  docs/source/components/index.md
  docs/source/components/rewoo-agent.md
  examples/agents/README.md
  examples/multi_frameworks/README.md
  examples/multi_frameworks/pyproject.toml
  examples/multi_frameworks/src/aiq_multi_frameworks/configs/config.yml
  examples/multi_frameworks/src/aiq_multi_frameworks/langchain_research_tool.py
  examples/plot_charts/src/aiq_plot_charts/register.py
  examples/simple_rag/README.md
Labels: improvement, non-breaking

#246 Consolidate MCP client and server docs, examples
  docs/source/components/index.md
  docs/source/guides/index.md
  docs/source/guides/mcp-client.md
  docs/source/guides/mcp-server.md
  docs/source/index.md
  docs/source/intro/why-aiqtoolkit.md
  examples/simple_calculator/README.md
  examples/simple_calculator/deploy_external_mcp/Dockerfile
  examples/simple_calculator/deploy_external_mcp/README.md
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-mcp-date.yml
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-mcp-math.yml
Labels: improvement, non-breaking

#257 Update version of llama-index to 0.12.21
  packages/aiqtoolkit_llama_index/pyproject.toml
  uv.lock
Labels: improvement, non-breaking

#256 [AIQ][25.05][RC3] Example to showcase Metadata support
  examples/simple_calculator/README.md
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-metadata.yml
  src/aiq/tool/register.py
  src/aiq/tool/server_tools.py
Labels: feature request, non-breaking, ! - Release

#253 mem: If conversation is not provided build it from memory
  src/aiq/memory/models.py
  src/aiq/tool/memory_tools/add_memory_tool.py
Labels: bug, non-breaking

#260 Prompt engineering to force `ReAct` agent to use memory for `simple_rag` example
  examples/simple_rag/configs/milvus_memory_rag_config.yml
  src/aiq/tool/register.py
Labels: bug, non-breaking

#259 simple-calculator: Additional input validation
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-tunable-rag-eval.yml
  examples/simple_calculator/src/aiq_simple_calculator/data/simple_calculator.json
  examples/simple_calculator/src/aiq_simple_calculator/register.py
Labels: bug, non-breaking

#266 Removed simple_mcp example
  examples/simple_mcp/README.md
  examples/simple_mcp/configs/config.yml
  examples/simple_mcp/deployment/docker-compose.yml
  examples/simple_mcp/servers/Dockerfile.proxy
  examples/simple_mcp/servers/run_fetch.sh
Labels: bug, non-breaking

#267 mcp-client.md: Add a note to check that the MCP time-service is running
  docs/source/workflows/mcp/mcp-client.md
Labels: doc, non-breaking

#271 Remove username from `README` log
  examples/email_phishing_analyzer/README.md
  examples/por_to_jiratickets/README.md
Labels: improvement, non-breaking

#263 Enhance error handling in MCP tool invocation
  src/aiq/tool/mcp/mcp_tool.py
Labels: bug, non-breaking

#274 Resolves a linting error in MCP tool
  src/aiq/tool/mcp/mcp_tool.py
Labels: bug, non-breaking, ! - Release

#270 Fix long-term memory issues of `semantic_kernel` example
  examples/semantic_kernel_demo/src/aiq_semantic_kernel_demo/configs/config.yml
  examples/semantic_kernel_demo/src/aiq_semantic_kernel_demo/register.py
  src/aiq/tool/mcp/mcp_tool.py
Labels: bug, non-breaking

#277 Change the example input for `Multi Frameworks` example
  examples/multi_frameworks/README.md
  examples/multi_frameworks/src/aiq_multi_frameworks/langchain_research_tool.py
Labels: improvement, non-breaking

#269 Fix intermediate steps parents when the parent is a Tool
  examples/profiler_agent/src/aiq_profiler_agent/register.py
  src/aiq/builder/context.py
  src/aiq/builder/intermediate_step_manager.py
  src/aiq/front_ends/fastapi/step_adaptor.py
  src/aiq/observability/async_otel_listener.py
  tests/aiq/builder/test_intermediate_step_manager.py
  tests/aiq/front_ends/fastapi/test_step_adaptor.py
Labels: bug, non-breaking

#278 Set mcp-proxy version in the sample Dockerfile to 0.5
  examples/simple_calculator/deploy_external_mcp/Dockerfile
Labels: bug, non-breaking

#279 Fix missing tool issue with `profiler_agent` example
  examples/profiler_agent/README.md
  examples/profiler_agent/src/aiq_profiler_agent/register.py
Labels: bug, non-breaking

#280 eval-readme: Add instruction to copy the workflow output before re-runs
  docs/source/reference/evaluate.md
Labels: bug, non-breaking

#282 Add additional notes for intermittent long-term memory issues in examples
  examples/semantic_kernel_demo/README.md
  examples/simple_rag/README.md
Labels: doc, non-breaking

#283 Run tests on all supported versions of Python
  .github/workflows/ci_pipe.yml
  .github/workflows/pr.yaml
  ci/scripts/github/tests.sh
Labels: improvement, non-breaking

#291 Changelog updated for 1.1.0
  CHANGELOG.md
Labels: doc, non-breaking

#292 Changelog updated for 1.1.0 (#291)
  CHANGELOG.md
Labels: doc, non-breaking

#293 Use consistent casing for ReAct agent
  docs/source/workflows/about/react-agent.md
  examples/agents/react/README.md
Labels: doc, non-breaking

#297 Update alert triage agent's prompt
  examples/alert_triage_agent/src/aiq_alert_triage_agent/prompts.py
Labels: bug, non-breaking

#237 Move Wikipedia search to separate file
  packages/aiqtoolkit_langchain/src/aiq/plugins/langchain/tools/register.py
  packages/aiqtoolkit_langchain/src/aiq/plugins/langchain/tools/tavily_internet_search.py
  packages/aiqtoolkit_langchain/src/aiq/plugins/langchain/tools/wikipedia_search.py
Labels: improvement, non-breaking

#300 Release documentation fixes
  ci/release/update-version.sh
  ci/scripts/gitlab/build_wheel.sh
  docs/source/release-notes.md
Labels: bug, non-breaking

#294 Update version in develop, in prep for the next release
  examples/agno_personal_finance/pyproject.toml
  examples/alert_triage_agent/pyproject.toml
  examples/automated_description_generation/pyproject.toml
  examples/documentation_guides/workflows/text_file_ingest/pyproject.toml
  examples/email_phishing_analyzer/pyproject.toml
  examples/multi_frameworks/pyproject.toml
  examples/plot_charts/pyproject.toml
  examples/por_to_jiratickets/pyproject.toml
  examples/profiler_agent/pyproject.toml
  examples/semantic_kernel_demo/pyproject.toml
  examples/simple/pyproject.toml
  examples/simple_calculator/pyproject.toml
  examples/swe_bench/pyproject.toml
  packages/aiqtoolkit_agno/pyproject.toml
  packages/aiqtoolkit_crewai/pyproject.toml
  packages/aiqtoolkit_langchain/pyproject.toml
  packages/aiqtoolkit_llama_index/pyproject.toml
  packages/aiqtoolkit_mem0ai/pyproject.toml
  packages/aiqtoolkit_semantic_kernel/pyproject.toml
  packages/aiqtoolkit_test/pyproject.toml
  packages/aiqtoolkit_weave/pyproject.toml
  packages/aiqtoolkit_zep_cloud/pyproject.toml
  packages/compat/agentiq/pyproject.toml
  packages/compat/agentiq_agno/pyproject.toml
  packages/compat/agentiq_crewai/pyproject.toml
  packages/compat/agentiq_langchain/pyproject.toml
  packages/compat/agentiq_mem0ai/pyproject.toml
  packages/compat/agentiq_test/pyproject.toml
  src/aiq/meta/pypi.md
  uv.lock
Labels: improvement, non-breaking

#312 Intermediate steps: evaluation fix
  src/aiq/eval/intermediate_step_adapter.py
  src/aiq/eval/rag_evaluator/evaluate.py
  src/aiq/eval/rag_evaluator/register.py
  tests/aiq/eval/rag_evaluator/test_rag_evaluate.py
  tests/aiq/eval/test_intermediate_step_adapter.py
Labels: improvement, non-breaking

#305 Fix or silence warnings emitted by tests
  examples/profiler_agent/src/aiq_profiler_agent/tool/flow_chart.py
  packages/aiqtoolkit_agno/tests/test_tool_wrapper.py
  packages/aiqtoolkit_mem0ai/tests/test_mem0_editor.py
  packages/aiqtoolkit_test/pyproject.toml
  packages/aiqtoolkit_test/src/aiq/test/embedder.py
  pyproject.toml
  src/aiq/cli/commands/start.py
  src/aiq/eval/evaluate.py
  src/aiq/observability/async_otel_listener.py
  src/aiq/profiler/inference_optimization/data_models.py
  src/aiq/profiler/inference_optimization/llm_metrics.py
  src/aiq/runtime/loader.py
  tests/aiq/builder/test_builder.py
  tests/aiq/builder/test_component_utils.py
  tests/aiq/eval/test_evaluate.py
  tests/aiq/front_ends/fastapi/test_fastapi_front_end_plugin.py
  tests/aiq/retriever/test_retrievers.py
  tests/aiq/utils/test_yaml_tools.py
  uv.lock
Labels: bug, non-breaking

#306 Add documentation for `load_workflow()`
  docs/source/workflows/run-workflows.md
Labels: doc, non-breaking

#194 Adding pytest-pretty for nice test outputs
  pyproject.toml
  uv.lock
Labels: improvement, non-breaking

#235 feat(telemetry): add langfuse and langsmith telemetry exporters #233
  ci/vale/styles/config/vocabularies/aiq/accept.txt
  docs/source/workflows/observe/index.md
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-langfuse.yml
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-langsmith.yml
  src/aiq/observability/register.py
Labels: feature request, non-breaking

#322 Eval doc updates
  docs/source/workflows/evaluate.md
Labels: doc, non-breaking

#329 Add missing import in `load_workflow` documentation
  docs/source/workflows/run-workflows.md
Labels: doc, non-breaking

#298 propose another solution to problem[copy]
  docs/source/troubleshooting.md
Labels: doc, non-breaking

#302 Support additional_instructions
  src/aiq/agent/react_agent/agent.py
  src/aiq/agent/react_agent/prompt.py
  src/aiq/agent/react_agent/register.py
  tests/aiq/agent/test_react.py
Labels: bug, non-breaking
