Repository NVIDIA/NeMo-Agent-Toolkit, pull requests merged in 2025-07, with the labels that each got.

#420 Update index.md
  docs/source/workflows/observe/index.md
Labels: doc, non-breaking

#423 Windows compatibility for temp file handling
  src/aiq/front_ends/fastapi/fastapi_front_end_plugin.py
Labels: bug, non-breaking

#424 Update and move W&B Weave Redact PII example
  docs/source/workflows/observe/observe-workflow-with-weave.md
  examples/intermediate/redact_pii/README.md
  examples/intermediate/redact_pii/images/redact_weave_trace.png
  examples/intermediate/redact_pii/pyproject.toml
  examples/intermediate/redact_pii/src/redact_pii/__init__.py
  examples/intermediate/redact_pii/src/redact_pii/configs/weave_redact_pii_config.yml
  examples/intermediate/redact_pii/src/redact_pii/register.py
  packages/aiqtoolkit_weave/pyproject.toml
  packages/aiqtoolkit_weave/src/aiq/plugins/weave/weave_sdk.py
  pyproject.toml
Labels: improvement, non-breaking

#330 Refactor IntermediateStep `parent_id` for clarification
  src/aiq/builder/intermediate_step_manager.py
  src/aiq/data_models/intermediate_step.py
  src/aiq/eval/remote_workflow.py
  src/aiq/observability/async_otel_listener.py
  tests/aiq/builder/test_intermediate_step_manager.py
  tests/aiq/eval/dataset_handler/test_dataset_handler.py
  tests/aiq/eval/test_evaluate.py
  tests/aiq/eval/test_intermediate_step_adapter.py
  tests/aiq/front_ends/fastapi/test_step_adaptor.py
  tests/aiq/profiler/metrics/test_common_prefixes.py
  tests/aiq/profiler/metrics/test_concurrency_spike.py
  tests/aiq/profiler/metrics/test_llm_metrics.py
  tests/aiq/profiler/metrics/test_nested_bottleneck.py
  tests/aiq/profiler/metrics/test_prefix_span.py
  tests/aiq/profiler/metrics/test_simple_bottleneck.py
  tests/aiq/profiler/metrics/test_token_uniqueness.py
  tests/aiq/profiler/test_callback_handler.py
  tests/aiq/profiler/test_profiler.py
  tests/conftest.py
Labels: bug, non-breaking

#426 Add Cursor rules for latinisms
  .cursor/rules/documentation/general.mdc
  .cursor/rules/documentation/latinisms.mdc
Labels: improvement, non-breaking

#429 Resolve examples organziation drift
  examples/README.md
  examples/intermediate/HITL/simple_calculator_hitl/README.md
  examples/intermediate/HITL/simple_calculator_hitl/src/aiq_simple_calculator_hitl/configs/config-hitl.yml
  examples/intermediate/observability/redact_pii/README.md
  examples/intermediate/observability/redact_pii/configs/weave_redact_pii_config.yml
  examples/intermediate/observability/redact_pii/images/redact_weave_trace.png
  examples/intermediate/observability/redact_pii/pyproject.toml
  examples/intermediate/observability/redact_pii/src/aiq_redact_pii/__init__.py
  examples/intermediate/observability/redact_pii/src/aiq_redact_pii/configs/weave_redact_pii_config.yml
  examples/intermediate/observability/redact_pii/src/aiq_redact_pii/register.py
  examples/intermediate/observability/simple_calculator_observability/README.md
  examples/intermediate/observability/simple_calculator_observability/configs/config-catalyst.yml
  pyproject.toml
  uv.lock
Labels: doc, non-breaking

#443 Improved logging for `langchain_web_ingest.py`
  .gitignore
  scripts/langchain_web_ingest.py
Labels: bug, non-breaking

#450 Update README to have more specific key feature section
  examples/src/agno_personal_finance/README.md
  examples/src/alert_triage_agent/README.md
  examples/src/automated_description_generation/README.md
  examples/src/email_phishing_analyzer/README.md
  examples/src/mixture_of_agents/README.md
  examples/src/multi_frameworks/README.md
  examples/src/plot_charts/README.md
  examples/src/por_to_jiratickets/README.md
  examples/src/profiler_agent/README.md
  examples/src/react/README.md
  examples/src/redact_pii/README.md
  examples/src/rewoo/README.md
  examples/src/semantic_kernel_demo/README.md
  examples/src/simple_calculator/README.md
  examples/src/simple_calculator_custom_routes/README.md
  examples/src/simple_calculator_eval/README.md
  examples/src/simple_calculator_hitl/README.md
  examples/src/simple_calculator_mcp/README.md
  examples/src/simple_calculator_observability/README.md
  examples/src/simple_rag/README.md
  examples/src/simple_web_query/README.md
  examples/src/simple_web_query_eval/README.md
  examples/src/swe_bench/README.md
  examples/src/tool_calling/README.md
Labels: improvement, non-breaking

#449 Refactor `plot_chart` example to improve reusability
  docs/source/_static/dual_node_agent.png
  docs/source/_static/reasoning_agent.png
  docs/source/_static/rewoo_agent.png
  examples/src/mixture_of_agents/README.md
  examples/src/plot_charts/README.md
  examples/src/plot_charts/src/aiq_plot_charts/configs/config.yml
  examples/src/plot_charts/src/aiq_plot_charts/create_plot.py
  examples/src/plot_charts/src/aiq_plot_charts/graph_instruction.py
  examples/src/plot_charts/src/aiq_plot_charts/plot_chain_agent.py
  examples/src/plot_charts/src/aiq_plot_charts/register.py
  examples/src/react/README.md
  examples/src/rewoo/README.md
  examples/src/simple_calculator/src/aiq_simple_calculator/configs/demo_config.yml
  examples/src/simple_web_query/Dockerfile
  examples/src/tool_calling/README.md
Labels: improvement, non-breaking

#453 Resolved errors in `simple_web_query` based examples caused from broken file paths and dependencies
  examples/src/simple_web_query/Dockerfile
  examples/src/simple_web_query/README.md
  examples/src/simple_web_query/data
  examples/src/simple_web_query/pyproject.toml
  examples/src/simple_web_query/tests/test_simple_web_query_workflow.py
  examples/src/simple_web_query_eval/README.md
  examples/src/simple_web_query_eval/configs
  examples/src/simple_web_query_eval/data
  examples/src/simple_web_query_eval/pyproject.toml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/__init__.py
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config_llama31.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config_llama33.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config_openai.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_only_config.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_upload.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/data/langsmith.csv
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/data/langsmith.json
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/data/langsmith.xlsx
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/data/langsmith_generated.json
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/data/simple_questions.json
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/scripts/__init__.py
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/scripts/workflow_to_csv.py
  examples/src/simple_web_query_eval/tests/test_simple_web_query_eval.py
  pyproject.toml
  uv.lock
Labels: bug, non-breaking

#451 Add otelcollector doc and example
  docs/source/workflows/observe/index.md
  docs/source/workflows/observe/observe-workflow-with-otel-collector.md
Labels: doc, non-breaking

#448 Update broken links in Profiler Agent README
  examples/src/profiler_agent/README.md
Labels: bug, non-breaking

#456 Revert `simple_web_query` examples' file paths in preparation for move to categorized folders
  examples/README.md
  examples/memory/README.md
  examples/src/simple_web_query/Dockerfile
  examples/src/simple_web_query/README.md
  examples/src/simple_web_query_eval/README.md
  examples/src/simple_web_query_eval/pyproject.toml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config_llama31.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config_llama33.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_config_openai.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_only_config.yml
  examples/src/simple_web_query_eval/src/aiq_simple_web_query_eval/configs/eval_upload.yml
  uv.lock
Labels: bug, non-breaking

#452 Update Configuration File Paths for Simple Calculator HITL and MCP Examples
  docs/source/workflows/mcp/mcp-client.md
Labels: bug, non-breaking

#458 Refactor RAGAS evaluators to account for NaN values in scores
  src/aiq/eval/rag_evaluator/evaluate.py
  tests/aiq/eval/rag_evaluator/test_rag_evaluate.py
Labels: bug, non-breaking

#468 Update Alert Triage Example with Offline Mode Instructions and Example
  examples/advanced_agents/alert_triage_agent/README.md
Labels: bug, non-breaking

#471 Fix: Docker setup and configuration for deploying external MCP
  examples/getting_started/simple_calculator/deploy_external_mcp/Dockerfile
  examples/getting_started/simple_calculator/deploy_external_mcp/README.md
Labels: bug, non-breaking

#473 Add S3 setup instructions for evaluation uploads
  examples/evaluation_and_profiling/simple_web_query_eval/README.md
Labels: doc, non-breaking

#462 Added automatic retry logic to clients and memory methods with exponential backoff
  packages/aiqtoolkit_agno/src/aiq/plugins/agno/llm.py
  packages/aiqtoolkit_crewai/src/aiq/plugins/crewai/llm.py
  packages/aiqtoolkit_langchain/src/aiq/plugins/langchain/embedder.py
  packages/aiqtoolkit_langchain/src/aiq/plugins/langchain/llm.py
  packages/aiqtoolkit_llama_index/src/aiq/plugins/llama_index/llm.py
  packages/aiqtoolkit_mem0ai/src/aiq/plugins/mem0ai/memory.py
  packages/aiqtoolkit_semantic_kernel/src/aiq/plugins/semantic_kernel/llm.py
  packages/aiqtoolkit_zep_cloud/src/aiq/plugins/zep_cloud/memory.py
  src/aiq/data_models/embedder.py
  src/aiq/data_models/llm.py
  src/aiq/data_models/memory.py
  src/aiq/data_models/retry_mixin.py
  src/aiq/embedder/nim_embedder.py
  src/aiq/embedder/openai_embedder.py
  src/aiq/llm/aws_bedrock_llm.py
  src/aiq/llm/nim_llm.py
  src/aiq/llm/openai_llm.py
  src/aiq/utils/exception_handlers/automatic_retries.py
  tests/aiq/utils/test_metadata_utils.py
  tests/aiq/utils/test_retry_wrapper.py
Labels: improvement, non-breaking

#477 Refactor Agno Personal Finance Function and Update Configuration
  examples/frameworks/agno_personal_finance/Dockerfile
  examples/frameworks/agno_personal_finance/README.md
  examples/frameworks/agno_personal_finance/configs
  examples/frameworks/agno_personal_finance/src/aiq_agno_personal_finance/agno_personal_finance_function.py
  examples/frameworks/agno_personal_finance/src/aiq_agno_personal_finance/configs/config.yml
  examples/getting_started/simple_calculator/README.md
  packages/aiqtoolkit_agno/src/aiq/plugins/agno/llm.py
  packages/aiqtoolkit_agno/src/aiq/plugins/agno/tools/serp_api_tool.py
  packages/aiqtoolkit_agno/tests/test_llm.py
  packages/aiqtoolkit_agno/tests/tools/test_serp_api_tool.py
Labels: bug, non-breaking

#421 Adding OpenAI Chat Completions API compatibility
  ci/vale/styles/config/vocabularies/aiq/accept.txt
  docs/source/reference/api-server-endpoints.md
  src/aiq/data_models/api_server.py
  src/aiq/front_ends/fastapi/fastapi_front_end_config.py
  src/aiq/front_ends/fastapi/fastapi_front_end_plugin_worker.py
  tests/aiq/front_ends/fastapi/test_openai_compatibility.py
Labels: feature request, non-breaking

#409 Enhance code execution sandbox with improved error handling and debugging
  src/aiq/tool/code_execution/README.md
  src/aiq/tool/code_execution/code_sandbox.py
  src/aiq/tool/code_execution/local_sandbox/.gitignore
  src/aiq/tool/code_execution/local_sandbox/local_sandbox_server.py
  src/aiq/tool/code_execution/local_sandbox/sandbox.requirements.txt
  src/aiq/tool/code_execution/local_sandbox/start_local_sandbox.sh
  src/aiq/tool/code_execution/register.py
  src/aiq/tool/code_execution/test_code_execution_sandbox.py
  tests/aiq/tools/test_code_execution.py
Labels: improvement, non-breaking

#483 Integrate latest `RetryMixin` fixes with `aiqtoolkit_agno` subpackage
  packages/aiqtoolkit_agno/src/aiq/plugins/agno/llm.py
Labels: improvement, non-breaking

#482 Fix incorrect file paths in simple calculator example
  examples/getting_started/simple_calculator/Dockerfile
  examples/getting_started/simple_calculator/README.md
  src/aiq/observability/mixin/file_mixin.py
  src/aiq/observability/mixin/file_mode.py
  src/aiq/observability/register.py
  tests/aiq/observability/mixin/test_file_mixin.py
Labels: bug, non-breaking

#436 Documentation edits for sizing calculator
  docs/source/workflows/sizing-calc.md
Labels: doc, non-breaking

#484 Update `git clone` under `/doc` folder to point to `main` branch
  docs/source/quick-start/installing.md
Labels: doc, non-breaking

#488 Fix `otelcollector` to ensure project name is added to `OtelSpan` resource + added weave cleanup logic
  packages/aiqtoolkit_opentelemetry/pyproject.toml
  packages/aiqtoolkit_opentelemetry/src/aiq/plugins/opentelemetry/mixin/otlp_span_exporter_mixin.py
  packages/aiqtoolkit_opentelemetry/src/aiq/plugins/opentelemetry/otel_span_exporter.py
  packages/aiqtoolkit_opentelemetry/src/aiq/plugins/opentelemetry/register.py
  packages/aiqtoolkit_opentelemetry/tests/observability/test_otel_span_adapter_exporter.py
  packages/aiqtoolkit_opentelemetry/tests/observability/test_otel_span_adapter_integration.py
  packages/aiqtoolkit_weave/src/aiq/plugins/weave/mixins/weave_mixin.py
  packages/aiqtoolkit_weave/src/aiq/plugins/weave/weave_exporter.py
  uv.lock
Labels: bug, non-breaking

#489 Fix shared field reference bug in `TypedBaseModel` inheritance
  src/aiq/data_models/common.py
  tests/aiq/data_models/test_common.py
Labels: bug, non-breaking

#501 Set SCM versioning for `text_file_ingest` allowing it to be built in CI
  ci/scripts/gitlab/build_wheel.sh
  docs/source/tutorials/create-a-new-workflow.md
  examples/documentation_guides/workflows/text_file_ingest/pyproject.toml
Labels: bug, non-breaking

#505 Fix `pyproject.toml` for `text_file_ingest` example
  docs/source/tutorials/create-a-new-workflow.md
  examples/documentation_guides/workflows/text_file_ingest/pyproject.toml
Labels: bug, non-breaking

#504 Clarify intermediate output formatting in agent tool_calling example
  examples/agents/tool_calling/README.md
Labels: doc, non-breaking

#511 Fix UI docs to launch the simple calculator
  docs/source/quick-start/launching-ui.md
Labels: doc, non-breaking

#515 Fix HITL `por_to_jiratickets` example
  examples/HITL/por_to_jiratickets/README.md
  examples/HITL/por_to_jiratickets/src/aiq_por_to_jiratickets/configs/config.yml
Labels: bug, non-breaking

#520 Documentation: Specify minimum uv version
  README.md
  docs/source/quick-start/installing.md
Labels: doc, non-breaking

#523 Fix issue where aiq fails for certain log levels
  src/aiq/front_ends/console/console_front_end_plugin.py
  src/aiq/front_ends/simple_base/simple_front_end_plugin_base.py
Labels: bug, non-breaking

#492 Update catalyst readme document
  docs/source/_static/ragaai_catalyst_traceview.png
  docs/source/workflows/observe/observe-workflow-with-catalyst.md
Labels: doc, non-breaking

#526 Fix outdated file references under `/examples`
  docs/source/workflows/workflow-configuration.md
  examples/HITL/simple_calculator_hitl/README.md
  examples/advanced_agents/alert_triage_agent/README.md
  examples/evaluation_and_profiling/email_phishing_analyzer/configs/config-reasoning.yml
  examples/observability/redact_pii/README.md
Labels: bug, non-breaking

#528 Misc cleanups/fixes for `installing.md` document
  ci/markdown-link-check-config.json
  docs/source/extend/functions.md
  docs/source/extend/sharing-components.md
  docs/source/quick-start/installing.md
  docs/source/reference/cli.md
  docs/source/resources/contributing.md
  docs/source/workflows/mcp/mcp-client.md
  examples/custom_functions/automated_description_generation/README.md
Labels: doc, non-breaking

#532 Resolve batch flushing failure during `SpanExporter` cleanup
  packages/aiqtoolkit_opentelemetry/src/aiq/plugins/opentelemetry/otel_span_exporter.py
  src/aiq/observability/exporter/processing_exporter.py
  src/aiq/observability/exporter/span_exporter.py
  src/aiq/observability/processor/batching_processor.py
  src/aiq/observability/processor/callback_processor.py
  src/aiq/observability/processor/processor.py
  tests/aiq/observability/exporter/test_processing_exporter.py
  tests/aiq/observability/processor/test_batching_processor.py
Labels: bug, non-breaking

#498 Publish the linear fit data in the CalcRunner Output
  docs/source/workflows/sizing-calc.md
  src/aiq/cli/commands/sizing/calc.py
  src/aiq/profiler/calc/calc_runner.py
  src/aiq/profiler/calc/data_models.py
Labels: improvement, non-breaking

#539 Restructure example README to fully align with reorganization
  examples/README.md
Labels: doc, non-breaking

#540 Fix grammar error in uninstall help string
  docs/source/reference/cli.md
  src/aiq/cli/commands/uninstall.py
Labels: doc, non-breaking

#541 Fix: custom routing example typos and output clarification
  examples/front_ends/simple_calculator_custom_routes/README.md
  src/aiq/tool/server_tools.py
Labels: bug, non-breaking

#542 Fix: Examples README output clarifications; installation command
  examples/RAG/simple_rag/README.md
  examples/advanced_agents/alert_triage_agent/README.md
Labels: bug, non-breaking

#513 Ensure type system and functional behavior are consistent for `to_type` specifications
  src/aiq/builder/function.py
  src/aiq/builder/function_base.py
  src/aiq/utils/type_converter.py
  tests/aiq/builder/test_function.py
  tests/aiq/runner/test_runner.py
Labels: bug, non-breaking

#546 Update the dataset in the swe-bench README
  examples/evaluation_and_profiling/swe_bench/README.md
Labels: doc, non-breaking

#545 Fix alert triage agent documentation on system output
  examples/advanced_agents/alert_triage_agent/README.md
Labels: doc, non-breaking

#547 Fix several dependency and documentation issues under `/examples`
  examples/HITL/por_to_jiratickets/README.md
  examples/MCP/simple_calculator_mcp/README.md
  examples/MCP/simple_calculator_mcp/configs/config-combined.yml
  examples/evaluation_and_profiling/simple_web_query_eval/pyproject.toml
  examples/frameworks/semantic_kernel_demo/pyproject.toml
Labels: bug, non-breaking

#548 Fixes to the `add-tools-to-a-workflow.md` tutorial
  docs/source/tutorials/add-tools-to-a-workflow.md
  examples/documentation_guides/workflows/custom_workflow/custom_config.yml
Labels: doc, non-breaking
