Repository NVIDIA/NeMo-Agent-Toolkit, pull requests merged in 2025-10, with the labels that each got.

#881 feat: LiteLLM support for LangChain/LangGraph, Agno, CrewAI, LlamaIndex
  docs/source/workflows/llms/index.md
  packages/nvidia_nat_agno/src/nat/plugins/agno/llm.py
  packages/nvidia_nat_crewai/src/nat/plugins/crewai/llm.py
  packages/nvidia_nat_langchain/pyproject.toml
  packages/nvidia_nat_langchain/src/nat/plugins/langchain/llm.py
  packages/nvidia_nat_llama_index/pyproject.toml
  packages/nvidia_nat_llama_index/src/nat/plugins/llama_index/llm.py
  src/nat/cli/main.py
  uv.lock
Labels: feature request, non-breaking

#885 fix: ensure registration of adk demo functions; reduce warnings
  examples/frameworks/adk_demo/src/nat_adk_demo/nat_time_mcp_tool.py
  examples/frameworks/adk_demo/src/nat_adk_demo/weather_update_tool.py
Labels: bug, non-breaking

#886 PyPi package install README updates
  README.md
  docs/source/extend/telemetry-exporters.md
  docs/source/quick-start/installing.md
  docs/source/reference/api-server-endpoints.md
  docs/source/reference/evaluate-api.md
  docs/source/workflows/evaluate.md
  docs/source/workflows/mcp/index.md
  docs/source/workflows/mcp/mcp-client.md
  docs/source/workflows/mcp/mcp-server.md
  docs/source/workflows/profiler.md
  examples/MCP/simple_auth_mcp/README.md
  examples/RAG/simple_rag/configs/milvus_memory_rag_tools_config.yml
  examples/RAG/simple_rag/configs/milvus_rag_tools_config.yml
  pyproject.toml
  src/nat/agent/prompt_optimizer/register.py
  src/nat/profiler/decorators/framework_wrapper.py
  src/nat/profiler/forecasting/models/linear_model.py
  src/nat/profiler/forecasting/models/random_forest_regressor.py
  src/nat/profiler/inference_optimization/bottleneck_analysis/nested_stack_analysis.py
  src/nat/profiler/inference_optimization/experimental/prefix_span_analysis.py
Labels: doc, non-breaking

#890 Fix notebook link to install instructions
  examples/notebooks/1_getting_started.ipynb
Labels: doc, non-breaking

#851 Improve new workflow template
  src/nat/cli/commands/workflow/templates/config.yml.j2
  src/nat/cli/commands/workflow/templates/register.py.j2
  src/nat/cli/commands/workflow/templates/workflow.py.j2
  src/nat/cli/commands/workflow/workflow_commands.py
Labels: improvement, non-breaking

#899 chore: additional workflow template cleanup
  src/nat/cli/commands/workflow/templates/config.yml.j2
  src/nat/cli/commands/workflow/templates/register.py.j2
  src/nat/cli/commands/workflow/templates/workflow.py.j2
Labels: improvement, non-breaking

#900 fix: documentation CLI tree update
  docs/source/reference/cli.md
Labels: doc, non-breaking

#863 Add hierarchical IDs for consistent telemetry and reporting
  packages/nvidia_nat_opentelemetry/src/nat/plugins/opentelemetry/otel_span.py
  src/nat/builder/context.py
  src/nat/data_models/span.py
  src/nat/observability/exporter/span_exporter.py
  src/nat/runtime/runner.py
  src/nat/runtime/session.py
  tests/nat/opentelemetry/test_otel_span_ids.py
  tests/nat/runtime/test_runner.py
  tests/nat/runtime/test_runner_trace_ids.py
  tests/nat/runtime/test_session_traceparent.py
Labels: improvement, non-breaking, ! - Release

#901 Fix Google ADK Demo registration
  examples/frameworks/adk_demo/src/nat_adk_demo/register.py
Labels: bug, non-breaking

#903 Update MCP related CLI commands in `cli.md`
  docs/source/reference/cli.md
Labels: doc, non-breaking

#904 Implement deprecated decorator for deprecation notices
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/tool.py
  src/nat/utils/decorators.py
  tests/nat/utils/test_decorators.py
Labels: improvement, non-breaking

#906 Add missing plugins to list in `installing.md`
  docs/source/quick-start/installing.md
Labels: doc, non-breaking

#910 fix: haystack deep research example test failure
  examples/frameworks/haystack_deep_research_agent/tests/test_haystack_deep_research_agent.py
Labels: bug, non-breaking

#912 feat: Improve the developer journey for example notebooks
  ci/scripts/path_checks.py
  ci/vale/styles/config/vocabularies/nat/accept.txt
  examples/README.md
  examples/notebooks/1_getting_started.ipynb
  examples/notebooks/1_getting_started_with_nat.ipynb
  examples/notebooks/2_add_tools_and_agents.ipynb
  examples/notebooks/2_bringing_your_own_agent.ipynb
  examples/notebooks/3_adding_tools_and_agents.ipynb
  examples/notebooks/4_observability_evaluation_and_profiling.ipynb
  examples/notebooks/README.md
  examples/notebooks/first_search_agent/configs
  examples/notebooks/first_search_agent/pyproject.toml
  examples/notebooks/first_search_agent/src/nat_first_search_agent/__init__.py
  examples/notebooks/first_search_agent/src/nat_first_search_agent/configs/config.yml
  examples/notebooks/first_search_agent/src/nat_first_search_agent/configs/config_modified.yml
  examples/notebooks/first_search_agent/src/nat_first_search_agent/configs/config_react_agent.yml
  examples/notebooks/first_search_agent/src/nat_first_search_agent/first_search_agent_function.py
  examples/notebooks/first_search_agent/src/nat_first_search_agent/register.py
  examples/notebooks/first_search_agent/src/nat_first_search_agent/second_search_agent_function.py
  examples/notebooks/langchain_sample/langchain_agent.py
  examples/notebooks/retail_sales_agent/configs
  examples/notebooks/retail_sales_agent/data
  examples/notebooks/retail_sales_agent/pyproject.toml
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/__init__.py
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/configs/config.yml
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/configs/config_evaluation_and_profiling.yml
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/configs/config_multi_agent.yml
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/configs/config_multi_agent_hitl.yml
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/configs/config_tracing.yml
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/configs/config_with_rag.yml
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/data/eval_data.json
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/data/rag/product_catalog.md
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/data/retail_sales_data.csv
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/data_insight_tools.py
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/data_visualization_agent.py
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/data_visualization_tools.py
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/llama_index_rag_tool.py
  examples/notebooks/retail_sales_agent/src/nat_retail_sales_agent/register.py
  pyproject.toml
  src/nat/tool/memory_tools/get_memory_tool.py
  uv.lock
Labels: feature request, non-breaking

#913 feat: Improve the developer journey for example notebooks (part 2)
  ci/vale/styles/config/vocabularies/nat/accept.txt
  examples/notebooks/4_observability_evaluation_and_profiling.ipynb
Labels: improvement, non-breaking

#922 Improve multi-user MCP client handling
  docs/source/workflows/mcp/mcp-client.md
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/client_impl.py
Labels: improvement, non-breaking

#925 Avoid Pydantic serialization warning triggered by tests
  ci/scripts/github/tests.sh
  examples/frameworks/haystack_deep_research_agent/pyproject.toml
  examples/frameworks/haystack_deep_research_agent/tests/test_haystack_deep_research_agent.py
  packages/nvidia_nat_test/src/nat/test/plugin.py
  tests/conftest.py
  tests/nat/front_ends/auth_flow_handlers/test_websocket_flow_handler.py
Labels: improvement, non-breaking

#927 fix: haystack deep research agent must be part of examples
  examples/frameworks/haystack_deep_research_agent/pyproject.toml
  examples/frameworks/multi_frameworks/pyproject.toml
  pyproject.toml
  uv.lock
Labels: improvement, non-breaking

#929 fix: pin uvicorn to prevent nest_asyncio patch error
  pyproject.toml
  uv.lock
Labels: bug, non-breaking

#928 Silence several warnings being emitted by the tests
  src/nat/builder/component_utils.py
  tests/nat/builder/test_component_utils.py
  tests/nat/data_models/test_optimizable.py
  tests/nat/mcp/test_mcp_auth_provider.py
  tests/nat/mcp/test_mcp_token_storage.py
Labels: improvement, non-breaking

#944 Add opensearch service to CI
  .gitlab-ci.yml
Labels: improvement, non-breaking

#945 Add an integration test for the custom route front-end example
  examples/front_ends/simple_calculator_custom_routes/configs/config-metadata.yml
  examples/front_ends/simple_calculator_custom_routes/tests/test_simple_calculator_custom_routes.py
  packages/nvidia_nat_test/src/nat/test/utils.py
  tests/nat/front_ends/fastapi/test_fastapi_front_end_plugin.py
  tests/nat/front_ends/fastapi/test_openai_compatibility.py
Labels: improvement, non-breaking

#943 fix: move Google ADK agent example back to ADK example
  examples/frameworks/adk_demo/src/nat_adk_demo/agent.py
  examples/frameworks/adk_demo/src/nat_adk_demo/register.py
  packages/nvidia_nat_adk/src/nat/plugins/adk/register.py
  packages/nvidia_nat_test/src/nat/test/llm.py
  packages/nvidia_nat_test/tests/test_test_llm.py
Labels: improvement, non-breaking

#947 fix: ensure console logging is configurable
  examples/front_ends/simple_auth/src/nat_simple_auth/configs/config.yml
  src/nat/builder/workflow_builder.py
  src/nat/cli/entrypoint.py
  src/nat/data_models/config.py
  src/nat/front_ends/console/console_front_end_plugin.py
  src/nat/observability/register.py
Labels: bug, non-breaking

#950 docs: clarify the need for a separate venv for local vLLM
  docs/source/workflows/llms/using-local-llms.md
Labels: doc, non-breaking
