Repository NVIDIA/NeMo-Agent-Toolkit, pull requests merged in 2025-04, with the labels that each got.

#54 gitlab ci pipeline cleanup
  .gitlab-ci.yml
  ci/scripts/gitlab/artifactory_upload.sh
  ci/scripts/gitlab/trigger.sh
Labels: feature request, non-breaking

#55 Allow str or None for retriever description
  src/aiq/retriever/milvus/register.py
Labels: bug, non-breaking

#22 Fix case where res['categories'] = None
  packages/agentiq_mem0ai/src/aiq/plugins/mem0ai/mem0_editor.py
Labels: bug, non-breaking

#56 Misc CI improbements
  .github/workflows/ci_pipe.yml
  .github/workflows/pr.yaml
  ci/scripts/github/build_wheel.sh
  ci/scripts/github/common.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/tests.sh
Labels: improvement, non-breaking

#24 CI Documentation improvements
  docs/Makefile
  docs/source/conf.py
  src/aiq/eval/utils/__init__.py
Labels: doc, non-breaking

#62 Add missing `platformdirs` dependency
  pyproject.toml
  uv.lock
Labels: bug, non-breaking

#63 Fix `aiq` command error when the parent directory of `AIQ_CONFIG_DIR` does not exist
  src/aiq/settings/global_settings.py
Labels: bug, non-breaking

#61 Fix broken image link in multi_frameworks documentation
  docs/source/_static/aiq_multi_frameworks_agentic_schema.png
  examples/multi_frameworks/README.md
Labels: doc, non-breaking

#64 Updating doc string for AIQSessionManager class.
  src/aiq/runtime/session.py
Labels: improvement, non-breaking

#68 Fix ragas evaluate unit tests
  tests/aiq/eval/rag_evaluator/test_rag_evaluate.py
Labels: bug, non-breaking

#70 Normalize Gannt Chart Timestamps in Profiler Nested Stack Analysis
  src/aiq/profiler/inference_optimization/bottleneck_analysis/nested_stack_analysis.py
Labels: improvement, non-breaking

#59 Scripts for running CI locally
  ci/scripts/bootstrap_local_ci.sh
  ci/scripts/common.sh
  ci/scripts/github/common.sh
  ci/scripts/github/docs.sh
  ci/scripts/gitutils.py
  ci/scripts/run_ci_local.sh
  docs/source/advanced/contributing.md
  docs/source/advanced/index.md
  docs/source/advanced/running-ci-locally.md
Labels: improvement, non-breaking

#76 Update types for `topic` and `description` attributes in `AIQRetrieverConfig` to allow `None`
  src/aiq/tool/retriever.py
  tests/aiq/tools/test_retriever.py
Labels: bug, non-breaking

#71 Add support for customizing output and uploading it to remote storage (S3 bucket)
  docs/source/concepts/evaluate.md
  docs/source/guides/evaluate.md
  examples/simple/src/aiq_simple/configs/eval_upload_config.yml
  examples/simple/src/aiq_simple/scripts/workflow_to_csv.py
  pyproject.toml
  src/aiq/data_models/evaluate.py
  src/aiq/eval/evaluate.py
  src/aiq/eval/utils/output_uploader.py
  tests/aiq/eval/test_evaluate.py
  tests/aiq/eval/utils/test_output_uploader.py
  uv.lock
Labels: feature request, non-breaking

#73 Support ARM in CI
  .github/workflows/ci_pipe.yml
  ci/scripts/run_ci_local.sh
  ci/vale/styles/config/vocabularies/aiq/accept.txt
  docs/source/advanced/running-ci-locally.md
  docs/source/release-notes.md
  examples/simple/tests/test_web_query_tool.py
Labels: improvement, non-breaking

#85 Allow overriding configuration values not set in the YAML
  docs/source/concepts/evaluate.md
  src/aiq/cli/cli_utils/config_override.py
  src/aiq/data_models/common.py
  tests/aiq/cli/cli_utils/test_config_override.py
Labels: bug, non-breaking

#90 Update changelog for 1.1.0a1 alpha release
  CHANGELOG.md
Labels: doc, non-breaking

#93 Updated changelog with another bug fix
  CHANGELOG.md
Labels: doc, non-breaking

#94 Updated changelog with another bug fix (#93)
  CHANGELOG.md
Labels: doc, non-breaking

#81 Adjust how the base_sha is passed into the workflow
  .github/workflows/ci_pipe.yml
  .github/workflows/pr.yaml
Labels: bug, non-breaking

#57 Changes for evaluating remote workflows
  docs/source/guides/evaluate.md
  docs/source/guides/using-agentiq-ui-and-server.md
  src/aiq/data_models/intermediate_step.py
  src/aiq/eval/evaluate.py
  src/aiq/eval/remote_workflow.py
  src/aiq/front_ends/fastapi/fastapi_front_end_plugin_worker.py
  src/aiq/front_ends/fastapi/intermediate_steps_subscriber.py
  src/aiq/front_ends/fastapi/response_helpers.py
  tests/aiq/eval/test_evaluate.py
  tests/aiq/eval/test_remote_evaluate.py
Labels: feature request, non-breaking

#105 Fix a bug in our pytest plugin causing test coverage to be under-reported
  packages/agentiq_test/src/aiq/test/plugin.py
  pyproject.toml
  src/aiq/tool/github_tools/get_github_issue.py
  tests/aiq/front_ends/fastapi/test_fastapi_front_end_config.py
  tests/aiq/profiler/forecasting/test_model_trainer.py
  uv.lock
Labels: bug, non-breaking

#87 Docker container for AgentIQ
  docker/Dockerfile
  docker/build_container.sh
Labels: feature request, non-breaking

#106 Modify JSON serialization to handle non-serializable objects
  src/aiq/eval/dataset_handler/dataset_handler.py
Labels: bug, non-breaking

#112 Upload nightly builds and release builds to pypi
  ci/scripts/gitlab/artifactory_upload.sh
Labels: improvement, non-breaking

#116 Ensure tags are fetched prior to determining the version
  ci/scripts/gitlab/artifactory_upload.sh
  ci/scripts/gitlab/build_wheel.sh
  ci/scripts/gitlab/common.sh
Labels: improvement, non-breaking

#117 Fix CI variable value
  ci/scripts/gitlab/common.sh
Labels: improvement, non-breaking

#118 Use setuptools_scm environment variables to set the version
  ci/scripts/gitlab/artifactory_upload.sh
  ci/scripts/gitlab/build_wheel.sh
  ci/scripts/gitlab/common.sh
Labels: improvement, non-breaking

#119 Only set the setuptools_scm variable when performing a nightly build
  ci/scripts/gitlab/build_wheel.sh
Labels: improvement, non-breaking

#123 Add a release PR template
  ci/release/pr_code_freeze_template.md
Labels: improvement, non-breaking

#109 Add an async /evaluate endpoint to trigger evaluation jobs on a remote cluster
  docs/source/conf.py
  docs/source/guides/evaluate-api.md
  docs/source/guides/evaluate.md
  docs/source/guides/index.md
  docs/source/guides/using-agentiq-ui-and-server.md
  examples/simple/src/aiq_simple/configs/eval_config.yml
  examples/simple/src/aiq_simple/configs/eval_upload_config.yml
  examples/simple/src/aiq_simple/scripts/workflow_to_csv.py
  pyproject.toml
  src/aiq/eval/config.py
  src/aiq/eval/evaluate.py
  src/aiq/eval/utils/output_uploader.py
  src/aiq/front_ends/fastapi/fastapi_front_end_config.py
  src/aiq/front_ends/fastapi/fastapi_front_end_plugin_worker.py
  src/aiq/front_ends/fastapi/job_store.py
  tests/aiq/eval/utils/test_output_uploader.py
  tests/aiq/front_ends/fastapi/test_evaluate_endpoints.py
  uv.lock
Labels: feature request, non-breaking

#126 Update /evaluate endpoint doc
  docs/source/guides/evaluate-api.md
Labels: doc, non-breaking

#98 Add function tracking decorator and update IntermediateStep
  docs/source/concepts/profiler.md
  src/aiq/builder/workflow_builder.py
  src/aiq/data_models/intermediate_step.py
  src/aiq/eval/utils/output_uploader.py
  src/aiq/profiler/decroators/__init__.py
  src/aiq/profiler/decroators/framework_wrapper.py
  src/aiq/profiler/decroators/function_tracking.py
  tests/aiq/profiler/test_function_tracking.py
Labels: improvement, non-breaking

#132 Fix typo in aiq.profiler.decorators
  src/aiq/builder/workflow_builder.py
  src/aiq/profiler/decorators/__init__.py
  src/aiq/profiler/decorators/framework_wrapper.py
  src/aiq/profiler/decorators/function_tracking.py
  tests/aiq/profiler/test_function_tracking.py
Labels: improvement, non-breaking

#82 Update the start command to use `validate_schema`
  src/aiq/cli/commands/start.py
Labels: improvement, non-breaking

#139 Make kwargs optional to the eval output customizer scripts
  docs/source/concepts/evaluate.md
  examples/simple/src/aiq_simple/scripts/workflow_to_csv.py
  src/aiq/data_models/evaluate.py
Labels: feature request, non-breaking

#131 Add an example that shows simple_calculator running with a MCP service.
  examples/mcp_server/Dockerfile
  examples/mcp_server/README.md
  examples/simple_calculator/README.md
  examples/simple_calculator/src/aiq_simple_calculator/configs/config-mcp-client.yml
Labels: improvement, non-breaking

#141 add `gitdiagram` to README
  README.md
  docs/source/_static/agentiq_gitdiagram.png
Labels: improvement, non-breaking

#142 Updating HITL reference guide to instruct users to toggle ws mode and…
  docs/source/concepts/workflow-configuration.md
  docs/source/guides/create-customize-workflows.md
  docs/source/guides/locally-hosted-llms.md
  docs/source/references/interactive-models.md
  examples/documentation_guides/locally_hosted_llms/nim_config.yml
  examples/documentation_guides/locally_hosted_llms/vllm_config.yml
  examples/documentation_guides/workflows/custom_workflow/custom_config.yml
  examples/simple/README.md
  examples/simple/src/aiq_simple/configs/config.yml
  examples/simple/src/aiq_simple/configs/eval_config.yml
  examples/simple/src/aiq_simple/configs/eval_upload_config.yml
Labels: enhancement, non-breaking

#129 Add override option to the eval CLI command
  docs/source/guides/evaluate.md
  src/aiq/cli/commands/evaluate.py
  src/aiq/eval/config.py
  src/aiq/eval/evaluate.py
Labels: feature request, non-breaking

#107 Fix type hints and docstrings for `ModelTrainer`
  src/aiq/profiler/forecasting/model_trainer.py
  src/aiq/profiler/forecasting/models/linear_model.py
  src/aiq/profiler/forecasting/models/random_forest_regressor.py
  tests/aiq/eval/conftest.py
  tests/aiq/profiler/forecasting/test_model_trainer.py
  tests/conftest.py
Labels: bug, non-breaking

#137 Delete workflow confirmation check in CLI - #114
  src/aiq/cli/commands/workflow/workflow_commands.py
Labels: improvement, non-breaking

#136 Improve Agent logging
  examples/agents/mixture_of_agents/README.md
  examples/agents/react/README.md
  examples/agents/rewoo/README.md
  examples/agents/tool_calling/README.md
  examples/agno_personal_finance/README.md
  examples/automated_description_generation/README.md
  examples/email_phishing_analyzer/README.md
  examples/por_to_jiratickets/README.md
  examples/semantic_kernel_demo/src/aiq_semantic_kernel_demo/configs/config.yml
  examples/simple/README.md
  examples/simple_calculator/README.md
  examples/simple_rag/README.md
  src/aiq/agent/base.py
  src/aiq/agent/react_agent/agent.py
  src/aiq/agent/react_agent/register.py
  src/aiq/agent/reasoning_agent/reasoning_agent.py
  src/aiq/agent/rewoo_agent/agent.py
  src/aiq/agent/tool_calling_agent/agent.py
  src/aiq/agent/tool_calling_agent/register.py
  src/aiq/front_ends/console/console_front_end_plugin.py
  src/aiq/observability/async_otel_listener.py
  src/aiq/profiler/decorators/framework_wrapper.py
  tests/aiq/agent/test_rewoo.py
Labels: improvement, non-breaking

#146 Add nicer error message for agents without tools
  src/aiq/agent/react_agent/register.py
  src/aiq/agent/rewoo_agent/register.py
  src/aiq/agent/tool_calling_agent/register.py
Labels: improvement, non-breaking

#149 Add `colorama` to core dependency
  examples/multi_frameworks/pyproject.toml
  examples/plot_charts/pyproject.toml
  pyproject.toml
  uv.lock
Labels: bug, non-breaking

#153 Rename AIQ_COMPONENT_NAME, remove unused COMPONENT_NAME
  ci/scripts/gitlab/artifactory_upload.sh
Labels: bug, non-breaking

#154 Group wheels under a common `aiqtoolkit` directory
  ci/scripts/github/build_wheel.sh
  ci/scripts/gitlab/artifactory_upload.sh
  ci/scripts/gitlab/build_wheel.sh
Labels: improvement, non-breaking

#155 Fix wheel upload wildcards
  .gitlab-ci.yml
Labels: bug, non-breaking

#148 Support Python `3.11` for AgentIQ
  README.md
  examples/agno_personal_finance/pyproject.toml
  examples/automated_description_generation/pyproject.toml
  examples/documentation_guides/workflows/text_file_ingest/pyproject.toml
  examples/email_phishing_analyzer/pyproject.toml
  examples/multi_frameworks/pyproject.toml
  examples/plot_charts/pyproject.toml
  examples/semantic_kernel_demo/pyproject.toml
  examples/simple/pyproject.toml
  examples/simple_calculator/pyproject.toml
  examples/swe_bench/pyproject.toml
  packages/aiqtoolkit_agno/pyproject.toml
  packages/aiqtoolkit_crewai/pyproject.toml
  packages/aiqtoolkit_langchain/pyproject.toml
  packages/aiqtoolkit_llama_index/pyproject.toml
  packages/aiqtoolkit_mem0ai/pyproject.toml
  packages/aiqtoolkit_semantic_kernel/pyproject.toml
  packages/aiqtoolkit_test/pyproject.toml
  packages/aiqtoolkit_zep_cloud/pyproject.toml
  pyproject.toml
  src/aiq/builder/eval_builder.py
  src/aiq/builder/workflow_builder.py
  src/aiq/cli/commands/workflow/templates/pyproject.toml.j2
  src/aiq/data_models/component_ref.py
  src/aiq/utils/reactive/observable.py
  src/aiq/utils/type_utils.py
  tests/aiq/front_ends/fastapi/test_fastapi_front_end_plugin.py
  uv.lock
Labels: improvement, non-breaking

#159 fix pydantic version incompatibility, closes #74
  pyproject.toml
Labels: bug, non-breaking

#166 Create config file symlink with `aiq workflow create` command
  src/aiq/cli/commands/workflow/workflow_commands.py
Labels: feature request, non-breaking

#164 Rename generate/stream/full to generate/full and add filter_steps parameter
  docs/source/guides/using-aiqtoolkit-ui-and-server.md
  src/aiq/eval/remote_workflow.py
  src/aiq/front_ends/fastapi/fastapi_front_end_plugin_worker.py
  src/aiq/front_ends/fastapi/response_helpers.py
  tests/aiq/eval/test_remote_evaluate.py
Labels: improvement, non-breaking

#157 Add support for environment variable interpolation in config files
  docs/source/concepts/workflow-configuration.md
  pyproject.toml
  src/aiq/utils/io/yaml_tools.py
  tests/aiq/builder/test_component_utils.py
  tests/aiq/cli/cli_utils/test_validation.py
  tests/aiq/utils/test_yaml_tools.py
  uv.lock
Labels: feature request, non-breaking

#162 Consistent Trace Nesting in Parallel Function Calling
  src/aiq/builder/intermediate_step_manager.py
  src/aiq/observability/async_otel_listener.py
  src/aiq/profiler/callbacks/langchain_callback_handler.py
  tests/aiq/builder/test_intermediate_step_manager.py
Labels: bug, non-breaking

#177 Fix broken links in examples documentation
  examples/agents/README.md
  examples/agno_personal_finance/README.md
  examples/automated_description_generation/README.md
  examples/email_phishing_analyzer/README.md
  examples/simple_calculator/README.md
  examples/swe_bench/README.md
Labels: doc, non-breaking

#178 Remove support for Python `3.13`
  README.md
  examples/agno_personal_finance/pyproject.toml
  examples/automated_description_generation/pyproject.toml
  examples/documentation_guides/workflows/text_file_ingest/pyproject.toml
  examples/email_phishing_analyzer/pyproject.toml
  examples/multi_frameworks/pyproject.toml
  examples/plot_charts/pyproject.toml
  examples/semantic_kernel_demo/pyproject.toml
  examples/simple/pyproject.toml
  examples/simple_calculator/pyproject.toml
  examples/swe_bench/pyproject.toml
  packages/aiqtoolkit_agno/pyproject.toml
  packages/aiqtoolkit_crewai/pyproject.toml
  packages/aiqtoolkit_langchain/pyproject.toml
  packages/aiqtoolkit_llama_index/pyproject.toml
  packages/aiqtoolkit_mem0ai/pyproject.toml
  packages/aiqtoolkit_semantic_kernel/pyproject.toml
  packages/aiqtoolkit_test/pyproject.toml
  packages/aiqtoolkit_zep_cloud/pyproject.toml
  pyproject.toml
  src/aiq/cli/commands/workflow/templates/pyproject.toml.j2
  uv.lock
Labels: bug, non-breaking
