Repository NVIDIA/NeMo-Agent-Toolkit, pull requests merged in 2025-06, with the labels that each got.

#338 Update trajectory eval documentation
  docs/source/workflows/evaluate.md
Labels: doc, non-breaking

#343 Rename test mode to offline mode
  examples/alert_triage_agent/README.md
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_live_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_offline_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/benign_fallback_offline_data.json
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/offline_data.csv
  examples/alert_triage_agent/src/aiq_alert_triage_agent/hardware_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/host_performance_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/monitoring_process_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/network_connectivity_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/register.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_heartbeat_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_performance_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/utils.py
  examples/alert_triage_agent/tests/test_alert_triage_agent_workflow.py
  examples/alert_triage_agent/tests/test_maintenance_check.py
  examples/alert_triage_agent/tests/test_telemetry_metrics_host_heartbeat_check_tool.py
  examples/alert_triage_agent/tests/test_telemetry_metrics_host_performance_check_tool.py
  examples/alert_triage_agent/tests/test_utils.py
Labels: improvement, non-breaking

#344 Simplify offline mode with `aiq eval`
  examples/alert_triage_agent/README.md
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_live_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_offline_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/offline_data.json
  examples/alert_triage_agent/src/aiq_alert_triage_agent/register.py
  examples/alert_triage_agent/tests/test_alert_triage_agent_workflow.py
Labels: improvement, non-breaking

#346 fix mcp client schema creation in flat lists
  src/aiq/tool/mcp/mcp_client.py
  tests/aiq/tools/test_mcp.py
Labels: bug, non-breaking

#350 Refactor for better prompt and tool description organization
  examples/alert_triage_agent/src/aiq_alert_triage_agent/categorizer.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/hardware_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/host_performance_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/maintenance_check.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/monitoring_process_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/network_connectivity_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/prompts.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_analysis_agent.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_heartbeat_check_tool.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_host_performance_check_tool.py
  examples/alert_triage_agent/tests/test_host_performance_check_tool.py
Labels: improvement, non-breaking

#357 Extend `IntermediateStep` to support tool schemas in tool calling LLM requests
  src/aiq/data_models/intermediate_step.py
  src/aiq/observability/async_otel_listener.py
  src/aiq/profiler/callbacks/langchain_callback_handler.py
  tests/aiq/observability/test_async_otel_listener.py
Labels: improvement, non-breaking

#328 Update `OpenAIModelConfig` to support `stream_usage` option
  packages/aiqtoolkit_langchain/pyproject.toml
  packages/aiqtoolkit_langchain/src/aiq/plugins/langchain/llm.py
  src/aiq/llm/openai_llm.py
Labels: bug, non-breaking

#359 Rename to NeMo Agent toolkit
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_request_correction.yml
  .github/ISSUE_TEMPLATE/documentation_request_new.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitmodules
  CHANGELOG.md
  README.md
  docs/source/index.md
  docs/source/release-notes.md
  docs/source/resources/contributing.md
  docs/source/support.md
  examples/simple/tests/test_web_query_tool.py
  packages/aiqtoolkit_agno/src/aiq/meta/pypi.md
  packages/aiqtoolkit_crewai/src/aiq/meta/pypi.md
  packages/aiqtoolkit_langchain/src/aiq/meta/pypi.md
  packages/aiqtoolkit_llama_index/src/aiq/meta/pypi.md
  packages/aiqtoolkit_mem0ai/src/aiq/meta/pypi.md
  packages/aiqtoolkit_semantic_kernel/src/aiq/meta/pypi.md
  packages/aiqtoolkit_test/src/aiq/meta/pypi.md
  packages/aiqtoolkit_weave/src/aiq/meta/pypi.md
  packages/aiqtoolkit_zep_cloud/src/aiq/meta/pypi.md
  src/aiq/meta/pypi.md
  uv.lock
Labels: doc, non-breaking

#369 Expand Alert Triage Agent Offline Dataset
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/offline_data.csv
  examples/alert_triage_agent/src/aiq_alert_triage_agent/data/offline_data.json
  examples/alert_triage_agent/src/aiq_alert_triage_agent/utils.py
  examples/alert_triage_agent/tests/test_alert_triage_agent_workflow.py
  examples/alert_triage_agent/tests/test_utils.py
Labels: improvement, non-breaking

#373 Add Custom Classification Accuracy Evaluator for the Alert Triage Agent
  examples/alert_triage_agent/src/aiq_alert_triage_agent/classification_evaluator.py
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_offline_mode.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/register.py
  examples/simple_calculator/src/aiq_simple_calculator/configs/demo_config.yml
  examples/simple_calculator/src/aiq_simple_calculator/configs/demo_config_mcp.yml
Labels: improvement, non-breaking

#368 Added LLM retry logic to handle rate limiting LLM without frequent Exception
  docs/source/reference/evaluate.md
  src/aiq/eval/tunable_rag_evaluator/evaluate.py
  src/aiq/eval/tunable_rag_evaluator/register.py
  tests/aiq/eval/tunable_rag_evaluator/test_tunable_rag_evaluate.py
Labels: improvement, non-breaking

#374 Fixes Function and LambdaFunction classes to push active function instance names
  src/aiq/builder/function.py
  src/aiq/builder/workflow_builder.py
Labels: bug, non-breaking

#331 Add Job ID Appending to Output Directories and Maximum Folders Threshold
  docs/source/reference/evaluate.md
  src/aiq/data_models/evaluate.py
  src/aiq/eval/evaluate.py
  tests/aiq/eval/test_evaluate.py
Labels: improvement, non-breaking

#380 Add support for custom functions in bottleneck analysis
  src/aiq/profiler/inference_optimization/bottleneck_analysis/nested_stack_analysis.py
Labels: bug, non-breaking

#264 Add support for Weave evaluation
  examples/simple/src/aiq_simple/configs/eval_config_weave.yml
  packages/aiqtoolkit_weave/src/aiq/plugins/weave/weave_sdk.py
  src/aiq/eval/evaluate.py
  src/aiq/eval/utils/weave_eval.py
Labels: feature request, non-breaking

#390 Update the information displayed in the Weave Eval dashboard
  docs/source/_static/weave_eval_dataset_results.png
  docs/source/_static/weave_eval_summary.png
  docs/source/workflows/evaluate.md
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_offline_llama_31.yml
  examples/alert_triage_agent/src/aiq_alert_triage_agent/configs/config_offline_llama_33.yml
  examples/simple/src/aiq_simple/configs/eval_config_llama31.yml
  examples/simple/src/aiq_simple/configs/eval_config_llama33.yml
  examples/simple/src/aiq_simple/configs/eval_config_openai.yml
  src/aiq/data_models/evaluate.py
  src/aiq/data_models/profiler.py
  src/aiq/eval/evaluate.py
  src/aiq/eval/usage_stats.py
  src/aiq/eval/utils/weave_eval.py
  src/aiq/profiler/data_models.py
  src/aiq/profiler/profile_runner.py
  tests/aiq/eval/test_evaluate.py
Labels: improvement, non-breaking

#400 Ragas custom evaluation field in evaluator
  src/aiq/eval/rag_evaluator/evaluate.py
  src/aiq/eval/rag_evaluator/register.py
  tests/aiq/eval/rag_evaluator/test_rag_evaluate.py
Labels: improvement, non-breaking
