Repository NVIDIA/NeMo-Agent-Toolkit, pull requests merged in 2025-09, with the labels that each got.

#743 docs: use https GitHub URL for easier installation and contribution
  docs/source/quick-start/installing.md
  docs/source/resources/contributing.md
Labels: doc, non-breaking

#747 Fix issues in GPU Sizing Launchable Notebook
  examples/notebooks/launchables/GPU_Cluster_Sizing_with_NeMo_Agent_Toolkit.ipynb
Labels: bug, non-breaking

#750 fix(llm): resolve patch order to apply retry before thinking
  packages/nvidia_nat_agno/src/nat/plugins/agno/llm.py
  packages/nvidia_nat_crewai/src/nat/plugins/crewai/llm.py
  packages/nvidia_nat_langchain/src/nat/plugins/langchain/llm.py
  packages/nvidia_nat_llama_index/src/nat/plugins/llama_index/llm.py
  packages/nvidia_nat_semantic_kernel/src/nat/plugins/semantic_kernel/llm.py
Labels: bug, non-breaking

#751 Enhance `ProcessingExporter` system to support redaction of content in telemetry traces
  docs/source/workflows/observe/index.md
  packages/nvidia_nat_opentelemetry/src/nat/plugins/opentelemetry/__init__.py
  packages/nvidia_nat_opentelemetry/src/nat/plugins/opentelemetry/otlp_span_redaction_adapter_exporter.py
  packages/nvidia_nat_opentelemetry/src/nat/plugins/opentelemetry/register.py
  packages/nvidia_nat_opentelemetry/tests/observability/test_otlp_span_adapter_exporter.py
  packages/nvidia_nat_opentelemetry/tests/observability/test_otlp_span_adapter_integration.py
  packages/nvidia_nat_opentelemetry/tests/observability/test_otlp_span_redaction_adapter_exporter.py
  src/nat/observability/exporter/processing_exporter.py
  src/nat/observability/mixin/redaction_config_mixin.py
  src/nat/observability/mixin/tagging_config_mixin.py
  src/nat/observability/processor/header_redaction_processor.py
  src/nat/observability/processor/redaction_processor.py
  src/nat/observability/processor/span_tagging_processor.py
  tests/nat/observability/exporter/test_processing_exporter.py
  tests/nat/observability/processor/test_header_redaction_processor.py
  tests/nat/observability/processor/test_redaction_processor.py
  tests/nat/observability/processor/test_span_tagging_processor.py
Labels: feature request, non-breaking

#725 Fix async endpoints when using multiple workers
  packages/nvidia_nat_all/pyproject.toml
  pyproject.toml
  src/nat/front_ends/fastapi/dask_client_mixin.py
  src/nat/front_ends/fastapi/fastapi_front_end_config.py
  src/nat/front_ends/fastapi/fastapi_front_end_plugin.py
  src/nat/front_ends/fastapi/fastapi_front_end_plugin_worker.py
  src/nat/front_ends/fastapi/job_store.py
  src/nat/front_ends/fastapi/main.py
  src/nat/front_ends/fastapi/utils.py
  tests/_utils/dask_utils.py
  tests/conftest.py
  tests/nat/front_ends/auth_flow_handlers/test_websocket_flow_handler.py
  tests/nat/front_ends/fastapi/conftest.py
  tests/nat/front_ends/fastapi/test_evaluate_endpoints.py
  tests/nat/front_ends/fastapi/test_fastapi_front_end_plugin.py
  tests/nat/front_ends/fastapi/test_job_store.py
  tests/nat/tools/test_code_execution.py
  tests/test_data/echo.yaml
  uv.lock
Labels: bug, non-breaking

#767 Refactor OTLPSpanHeaderRedactionAdapterExporter to support multiple headers and Span tags
  packages/nvidia_nat_opentelemetry/src/nat/plugins/opentelemetry/otlp_span_redaction_adapter_exporter.py
  packages/nvidia_nat_opentelemetry/tests/observability/test_otlp_span_redaction_adapter_exporter.py
  src/nat/observability/exporter/processing_exporter.py
  src/nat/observability/mixin/redaction_config_mixin.py
  src/nat/observability/mixin/tagging_config_mixin.py
  src/nat/observability/mixin/type_introspection_mixin.py
  src/nat/observability/processor/header_redaction_processor.py
  src/nat/observability/processor/processor.py
  src/nat/observability/processor/redaction/__init__.py
  src/nat/observability/processor/redaction/contextual_redaction_processor.py
  src/nat/observability/processor/redaction/contextual_span_redaction_processor.py
  src/nat/observability/processor/redaction/redaction_processor.py
  src/nat/observability/processor/redaction/span_header_redaction_processor.py
  src/nat/observability/processor/redaction_processor.py
  src/nat/observability/processor/span_tagging_processor.py
  src/nat/utils/callable_utils.py
  src/nat/utils/type_utils.py
  tests/nat/observability/exporter/test_processing_exporter.py
  tests/nat/observability/exporter/test_raw_exporter.py
  tests/nat/observability/mixin/test_type_introspection_mixin.py
  tests/nat/observability/processor/redaction/test_contextual_redaction_processor.py
  tests/nat/observability/processor/redaction/test_contextual_span_redaction_processor.py
  tests/nat/observability/processor/redaction/test_redaction_processor.py
  tests/nat/observability/processor/redaction/test_span_header_redaction_processor.py
  tests/nat/observability/processor/test_batching_processor.py
  tests/nat/observability/processor/test_header_redaction_processor.py
  tests/nat/observability/processor/test_intermediate_step_serializer.py
  tests/nat/observability/processor/test_processor.py
  tests/nat/observability/processor/test_redaction_processor.py
  tests/nat/observability/processor/test_span_tagging_processor.py
  tests/nat/utils/test_type_utils.py
Labels: improvement, non-breaking

#772 fix: ensure `model_dump` excludes `None` fields when appropriate
  packages/nvidia_nat_crewai/src/nat/plugins/crewai/llm.py
  packages/nvidia_nat_langchain/src/nat/plugins/langchain/embedder.py
  packages/nvidia_nat_langchain/src/nat/plugins/langchain/llm.py
  packages/nvidia_nat_llama_index/src/nat/plugins/llama_index/embedder.py
Labels: bug, non-breaking

#785 Add `tool_call_max_retries` option to ReWOO agent
  docs/source/workflows/about/rewoo-agent.md
  examples/agents/rewoo/README.md
  examples/agents/rewoo/configs/config.yml
  src/nat/agent/rewoo_agent/agent.py
  src/nat/agent/rewoo_agent/register.py
  tests/nat/agent/test_rewoo.py
Labels: improvement, non-breaking

#786 Document async endpoint functionality
  ci/vale/styles/config/vocabularies/nat/accept.txt
  docs/source/reference/api-server-endpoints.md
  docs/source/reference/evaluate-api.md
  src/nat/front_ends/fastapi/fastapi_front_end_config.py
  src/nat/front_ends/fastapi/fastapi_front_end_plugin.py
  src/nat/front_ends/fastapi/job_store.py
Labels: doc, non-breaking

#790 Fix workflow create documentation and command
  ci/scripts/common.sh
  docs/source/tutorials/create-a-new-workflow.md
  src/nat/cli/commands/workflow/workflow_commands.py
  tests/nat/cli/commands/test_workflow_commands.py
Labels: bug, non-breaking

#792 Fix `run_ci_local.sh` to not prompt for username/password
  ci/scripts/bootstrap_local_ci.sh
  ci/scripts/common.sh
  ci/scripts/run_ci_local.sh
Labels: bug, non-breaking

#775 Add return_direct option to tool_calling_agent for direct tool responses
  docs/source/workflows/about/tool-calling-agent.md
  src/nat/agent/tool_calling_agent/agent.py
  src/nat/agent/tool_calling_agent/register.py
  tests/nat/agent/test_tool_calling.py
Labels: feature request, non-breaking

#793 Document the NeMo-Agent-Toolkit-Examples repo
  docs/source/resources/contributing.md
  examples/README.md
Labels: doc, non-breaking

#787 fix(cli): nat workflow create should validate workflow name
  src/nat/cli/commands/workflow/workflow_commands.py
  tests/nat/cli/commands/test_workflow_commands.py
Labels: bug, non-breaking, external

#801 Fix issue where optimizable params are in model dump
  src/nat/data_models/optimizable.py
Labels: bug, non-breaking

#803 Prevent retry storms in nested method calls
  src/nat/utils/exception_handlers/automatic_retries.py
  tests/nat/utils/test_retry_wrapper.py
Labels: bug, non-breaking

#804 Fix the `test_unified_api_server` integration tests
  ci/scripts/gitlab/report_test_results.py
  ci/scripts/gitlab/tests.sh
  tests/nat/server/test_unified_api_server.py
Labels: bug, non-breaking

#684 feat!: Implement Function Groups
  ci/scripts/path_checks.py
  docs/source/extend/function-groups.md
  docs/source/index.md
  docs/source/workflows/function-groups.md
  examples/object_store/user_report/README.md
  examples/object_store/user_report/configs/config_mem.yml
  examples/object_store/user_report/configs/config_mysql.yml
  examples/object_store/user_report/configs/config_redis.yml
  examples/object_store/user_report/configs/config_s3.yml
  examples/object_store/user_report/src/nat_user_report/user_report_tools.py
  packages/nvidia_nat_test/src/nat/test/tool_test_runner.py
  src/nat/agent/react_agent/register.py
  src/nat/agent/reasoning_agent/reasoning_agent.py
  src/nat/agent/rewoo_agent/register.py
  src/nat/agent/tool_calling_agent/register.py
  src/nat/builder/builder.py
  src/nat/builder/component_utils.py
  src/nat/builder/function.py
  src/nat/builder/workflow.py
  src/nat/builder/workflow_builder.py
  src/nat/cli/register_workflow.py
  src/nat/cli/type_registry.py
  src/nat/data_models/component.py
  src/nat/data_models/component_ref.py
  src/nat/data_models/config.py
  src/nat/data_models/function.py
  src/nat/data_models/function_dependencies.py
  src/nat/experimental/test_time_compute/functions/plan_select_execute_function.py
  src/nat/front_ends/mcp/mcp_front_end_plugin_worker.py
  src/nat/profiler/utils.py
  src/nat/tool/github_tools.py
  src/nat/tool/github_tools/__init__.py
  src/nat/tool/github_tools/create_github_commit.py
  src/nat/tool/github_tools/create_github_issue.py
  src/nat/tool/github_tools/create_github_pr.py
  src/nat/tool/github_tools/get_github_file.py
  src/nat/tool/github_tools/get_github_issue.py
  src/nat/tool/github_tools/get_github_pr.py
  src/nat/tool/github_tools/update_github_issue.py
  src/nat/tool/register.py
  tests/nat/agent/test_reasoning_agent.py
  tests/nat/builder/test_builder.py
  tests/nat/front_ends/mcp/test_mcp_custom_routes.py
Labels: feature request, breaking

#802 Fixes `chat_completion` returning wrong type and substitute `.content` with `.text()`
  examples/advanced_agents/alert_triage_agent/src/nat_alert_triage_agent/categorizer.py
  examples/advanced_agents/alert_triage_agent/src/nat_alert_triage_agent/host_performance_check_tool.py
  examples/advanced_agents/alert_triage_agent/src/nat_alert_triage_agent/utils.py
  examples/advanced_agents/profiler_agent/src/nat_profiler_agent/agent.py
  examples/custom_functions/automated_description_generation/src/nat_automated_description_generation/utils/workflow_utils.py
  packages/nvidia_nat_langchain/src/nat/plugins/langchain/tools/code_generation_tool.py
  src/nat/tool/chat_completion.py
Labels: bug, non-breaking

#810 Move visualization import into method for Optimizer
  src/nat/profiler/parameter_optimization/parameter_optimizer.py
  tests/nat/profiler/test_parameter_optimizer.py
Labels: bug, non-breaking

#807 Add function group filtering
  docs/source/extend/function-groups.md
  docs/source/workflows/function-groups.md
  src/nat/builder/function.py
  tests/nat/builder/test_function_group.py
Labels: feature request, non-breaking

#812 Expanding nightly E2E tests
  .gitlab-ci.yml
  packages/nvidia_nat_mysql/tests/test_mysql_object_store.py
  packages/nvidia_nat_redis/tests/test_redis_object_store.py
  packages/nvidia_nat_s3/src/nat/plugins/s3/object_store.py
  packages/nvidia_nat_s3/tests/test_s3_object_store.py
  tests/conftest.py
Labels: improvement, non-breaking

#817 Move router agent to `control_flow` category
  docs/source/workflows/about/index.md
  docs/source/workflows/about/router-agent.md
  docs/source/workflows/about/sequential-executor.md
  examples/control_flow/router_agent/README.md
  examples/control_flow/router_agent/configs/config.yml
  examples/control_flow/router_agent/pyproject.toml
  examples/control_flow/router_agent/src/nat_router_agent/__init__.py
  examples/control_flow/router_agent/src/nat_router_agent/register.py
  examples/control_flow/router_agent/tests/test_router_agent.py
  examples/control_flow/sequential_executor/README.md
  pyproject.toml
  src/nat/agent/register.py
  src/nat/control_flow/register.py
  src/nat/control_flow/router_agent/__init__.py
  src/nat/control_flow/router_agent/agent.py
  src/nat/control_flow/router_agent/prompt.py
  src/nat/control_flow/router_agent/register.py
  src/nat/control_flow/sequential_executor.py
  tests/nat/agent/test_router_agent.py
  uv.lock
Labels: doc, non-breaking

#809 MCP OAuth2 Token Introspection Validator
  src/nat/authentication/credential_validator/__init__.py
  src/nat/authentication/credential_validator/bearer_token_validator.py
  src/nat/authentication/oauth2/oauth2_resource_server_config.py
  src/nat/data_models/authentication.py
  src/nat/front_ends/mcp/introspection_token_verifier.py
  src/nat/front_ends/mcp/mcp_front_end_config.py
  src/nat/front_ends/mcp/mcp_front_end_plugin.py
  tests/nat/authentication/test_bearer_token_validator.py
  tests/nat/authentication/test_oauth_resource_server_config.py
Labels: feature request, non-breaking

#825 Improved Dask shutdown
  pyproject.toml
  src/nat/cli/entrypoint.py
  src/nat/front_ends/fastapi/dask_client_mixin.py
  src/nat/front_ends/fastapi/fastapi_front_end_config.py
  src/nat/front_ends/fastapi/fastapi_front_end_plugin.py
  src/nat/utils/log_levels.py
  tests/nat/front_ends/fastapi/test_dask_client_mixin.py
  uv.lock
Labels: improvement, non-breaking

#826 fix: correct logic for `test_unified_api_server.py`
  tests/nat/server/test_unified_api_server.py
Labels: bug, non-breaking, external

#831 Fix `TraceAdapterRegistry` lookup errors in `SpanToDFWRecordProcessor`
  packages/nvidia_nat_data_flywheel/src/nat/plugins/data_flywheel/observability/processor/dfw_record_processor.py
  packages/nvidia_nat_data_flywheel/tests/observability/processor/test_dfw_record_processor.py
  src/nat/observability/mixin/type_introspection_mixin.py
  tests/nat/observability/mixin/test_type_introspection_mixin.py
Labels: bug, non-breaking

#833 Avoid calling 'git lfs install' as CI already performs this
  ci/scripts/common.sh
Labels: bug, non-breaking

#835 Add missing dependencies
  examples/control_flow/sequential_executor/pyproject.toml
Labels: bug, non-breaking

#847 Fix `chat_history` processing logic in ReAct agent
  examples/agents/react/configs/config.yml
  src/nat/agent/react_agent/agent.py
  tests/nat/agent/test_react.py
Labels: bug, non-breaking

#840 Improve robustness of MCP client remote tool calling
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/client_base.py
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/client_impl.py
  tests/nat/mcp/test_mcp_client_base.py
Labels: bug, non-breaking

#848 fix: improve Google ADK structure and fix callback handlers for tools and LLMs
  docs/source/index.md
  docs/source/quick-start/installing.md
  docs/source/workflows/observe/index.md
  docs/source/workflows/profiler.md
  examples/frameworks/adk_demo/README.md
  examples/frameworks/adk_demo/configs/config.yml
  examples/frameworks/adk_demo/configs/eval_config.yml
  examples/frameworks/adk_demo/data/eval.json
  examples/frameworks/adk_demo/src/nat_adk_demo/__init__.py
  examples/frameworks/adk_demo/src/nat_adk_demo/nat_time_mcp_tool.py
  examples/frameworks/adk_demo/src/nat_adk_demo/register.py
  examples/frameworks/adk_demo/src/nat_adk_demo/weather_update_tool.py
  examples/frameworks/agno_personal_finance/pyproject.toml
  examples/frameworks/multi_frameworks/pyproject.toml
  packages/nvidia_nat_adk/pyproject.toml
  packages/nvidia_nat_adk/src/nat/plugins/adk/__init__.py
  packages/nvidia_nat_adk/src/nat/plugins/adk/adk_callback_handler.py
  packages/nvidia_nat_adk/src/nat/plugins/adk/agent.py
  packages/nvidia_nat_adk/src/nat/plugins/adk/llm.py
  packages/nvidia_nat_adk/src/nat/plugins/adk/register.py
  packages/nvidia_nat_adk/tests/test_adk_callback_handler.py
  packages/nvidia_nat_adk/tests/test_adk_llm.py
  packages/nvidia_nat_agno/pyproject.toml
  packages/nvidia_nat_all/pyproject.toml
  packages/nvidia_nat_crewai/pyproject.toml
  packages/nvidia_nat_ragaai/pyproject.toml
  pyproject.toml
  src/nat/llm/litellm_llm.py
  src/nat/llm/register.py
  uv.lock
Labels: improvement, non-breaking

#854 MCP Client Auth Support (part-2)
  docs/source/workflows/mcp/index.md
  docs/source/workflows/mcp/mcp-auth.md
  docs/source/workflows/mcp/mcp-client.md
  examples/MCP/simple_auth_mcp/README.md
  examples/MCP/simple_auth_mcp/configs/config-mcp-auth-jira.yml
  examples/MCP/simple_auth_mcp/pyproject.toml
  examples/MCP/simple_calculator_mcp/configs/config-mcp-auth-math.yml
  examples/MCP/simple_calculator_mcp/configs/config-mcp-date-stdio.yml
  examples/MCP/simple_calculator_mcp/configs/config-mcp-server-auth.yml
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/auth/auth_flow_handler.py
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/auth/auth_provider.py
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/auth/auth_provider_config.py
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/client_base.py
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/client_impl.py
  pyproject.toml
  src/nat/authentication/api_key/api_key_auth_provider.py
  src/nat/authentication/http_basic_auth/http_basic_auth_provider.py
  src/nat/authentication/interfaces.py
  src/nat/authentication/oauth2/oauth2_auth_code_flow_provider.py
  src/nat/cli/commands/mcp/mcp.py
  src/nat/data_models/authentication.py
  src/nat/runtime/session.py
  tests/nat/cli/commands/mcp/test_mcp_cli.py
  tests/nat/mcp/test_mcp_auth_provider.py
  uv.lock
Labels: feature request, breaking

#853 Add `mcp/client/tool/list` endpoint
  docs/source/workflows/mcp/mcp-client.md
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/client_base.py
  packages/nvidia_nat_mcp/src/nat/plugins/mcp/client_impl.py
  src/nat/cli/commands/mcp/mcp.py
  src/nat/front_ends/fastapi/fastapi_front_end_plugin_worker.py
  tests/nat/front_ends/fastapi/test_mcp_client_endpoint.py
  tests/nat/mcp/test_mcp_client_base.py
Labels: feature request, non-breaking

#871 Declare `pip` as a direct dependency
  pyproject.toml
  uv.lock
Labels: bug, non-breaking

#877 MCP authentication Overview Doc
  docs/source/workflows/mcp/index.md
  docs/source/workflows/mcp/mcp-auth.md
  docs/source/workflows/mcp/mcp-client.md
  docs/source/workflows/mcp/mcp-server.md
  examples/MCP/simple_auth_mcp/README.md
Labels: doc, non-breaking
