Repository NVIDIA/NeMo-Agent-Toolkit, pull requests merged in 2025-08, with the labels that each got.

#549 Update Cursor rules and documentations to remove unnecessary installation checks
  .cursor/rules/aiq-setup/aiq-toolkit-installation.mdc
  docs/source/tutorials/build-a-demo-agent-workflow-using-cursor-rules.md
Labels: improvement, non-breaking

#552 Update `object_store` example to use NVIDIA key instead of missing OPENAI key
  examples/object_store/user_report/README.md
  examples/object_store/user_report/configs/config_mem.yml
  examples/object_store/user_report/configs/config_mysql.yml
  examples/object_store/user_report/configs/config_s3.yml
Labels: bug, non-breaking

#558 Update the LangSmith environment variable names in `simple_calculator_observability` example
  examples/observability/simple_calculator_observability/README.md
Labels: doc, non-breaking

#554 Improvements to extending telemetry exporters docs
  docs/source/extend/telemetry-exporters.md
  examples/observability/simple_calculator_observability/pyproject.toml
  src/aiq/observability/processor/callback_processor.py
  tests/aiq/observability/processor/test_batching_processor.py
  uv.lock
Labels: doc, non-breaking

#556 Misc cleanups for `create-a-new-workflow.md` document
  docs/source/tutorials/create-a-new-workflow.md
  examples/documentation_guides/workflows/text_file_ingest/src/text_file_ingest/text_file_ingest_function.py
Labels: doc, non-breaking

#563 Reduce the number of warnings logged while running the `getting_started` examples
  examples/getting_started/simple_web_query/src/aiq_simple_web_query/register.py
  src/aiq/cli/commands/start.py
  src/aiq/runtime/loader.py
Labels: improvement, non-breaking

#562 Update observability system documentation to reflect modern architecture and remove snippets
  docs/source/workflows/observe/index.md
Labels: doc, non-breaking

#561 Add docker container for oauth server to fix configuration issues
  examples/front_ends/simple_auth/Dockerfile
  examples/front_ends/simple_auth/README.md
  examples/front_ends/simple_auth/docker-compose.yml
  examples/front_ends/simple_auth/src/simple_auth/configs/config.yml
  examples/front_ends/simple_auth/src/simple_auth/ip_lookup.py
Labels: improvement, non-breaking, ! - Release

#564 Ensure imports are lazily loaded in plugins improving startup time
  examples/advanced_agents/alert_triage_agent/src/aiq_alert_triage_agent/categorizer.py
  examples/advanced_agents/alert_triage_agent/src/aiq_alert_triage_agent/maintenance_check.py
  examples/advanced_agents/alert_triage_agent/src/aiq_alert_triage_agent/register.py
  examples/advanced_agents/alert_triage_agent/src/aiq_alert_triage_agent/telemetry_metrics_analysis_agent.py
  examples/advanced_agents/alert_triage_agent/src/aiq_alert_triage_agent/utils.py
  examples/custom_functions/automated_description_generation/src/aiq_automated_description_generation/register.py
  examples/frameworks/multi_frameworks/src/aiq_multi_frameworks/langchain_research_tool.py
  examples/front_ends/simple_auth/pyproject.toml
  examples/front_ends/simple_auth/src/aiq_simple_auth/__init__.py
  examples/front_ends/simple_auth/src/aiq_simple_auth/configs/config.yml
  examples/front_ends/simple_auth/src/aiq_simple_auth/ip_lookup.py
  examples/front_ends/simple_auth/src/aiq_simple_auth/register.py
  src/aiq/agent/react_agent/register.py
  src/aiq/agent/reasoning_agent/reasoning_agent.py
  src/aiq/agent/tool_calling_agent/register.py
  src/aiq/runtime/loader.py
Labels: improvement, non-breaking

#555 General improvements to `observe-workflow-with-catalyst.md` to improve experience
  docs/source/workflows/observe/observe-workflow-with-catalyst.md
Labels: doc, non-breaking

#566 Update Simple Auth Example Config File Path
  examples/front_ends/simple_auth/configs/config.yml
Labels: bug, non-breaking, ! - Release

#577 Minor cleanups for `sizing-calc.md`
  docs/source/workflows/sizing-calc.md
Labels: doc, non-breaking

#582 minor doc update to pass lint
  docs/source/conf.py
  docs/source/workflows/using-local-llms.md
Labels: doc, non-breaking

#592 Fix module discovery errors when publishing with registry handlers
  packages/aiqtoolkit_opentelemetry/pyproject.toml
  packages/aiqtoolkit_opentelemetry/src/aiq/meta/pypi.md
  src/aiq/registry_handlers/package_utils.py
  tests/aiq/registry_handlers/test_package_utils.py
Labels: bug, non-breaking

#594 Fix fence indenting, remove ignore pattern
  ci/markdown-link-check-config.json
  docs/source/extend/telemetry-exporters.md
Labels: doc, non-breaking

#595 Minor cleanup to `using-local-llms.md`
  docs/source/workflows/using-local-llms.md
Labels: doc, non-breaking

#597 Merge Post VDR changes
  ci/scripts/checks.sh
  ci/scripts/github/checks.sh
  docs/source/resources/contributing.md
  examples/advanced_agents/vulnerability_analysis_blueprint/README.md
Labels: improvement, non-breaking

#605 Rename ITS tool functions to TTC tool functions
  src/aiq/experimental/test_time_compute/functions/ttc_tool_orchestration_function.py
  src/aiq/experimental/test_time_compute/functions/ttc_tool_wrapper_function.py
  src/aiq/experimental/test_time_compute/register.py
Labels: improvement, breaking

#609 Fix Pylint in CI
  .github/workflows/ci_pipe.yml
  ci/scripts/github/common.sh
  uv.lock
Labels: bug, non-breaking

#627 Fixes to `weave` telemetry exporter to ensure traces are properly sent to Weave
  packages/nvidia_nat_weave/src/nat/plugins/weave/mixins/_init__.py
  packages/nvidia_nat_weave/src/nat/plugins/weave/mixins/weave_mixin.py
  packages/nvidia_nat_weave/src/nat/plugins/weave/weave_exporter.py
Labels: bug, non-breaking

#630 Apply work-around for #621 to the gitlab ci scripts
  ci/scripts/gitlab/common.sh
Labels: bug, non-breaking

#631 Revert unintended change to `artifactory_upload.sh`
  ci/scripts/gitlab/artifactory_upload.sh
Labels: bug, non-breaking

#628 Bugfix (Object Store): remove unnecessary S3 refs in config; fix mysql upload script
  examples/object_store/user_report/configs/config_mem.yml
  examples/object_store/user_report/configs/config_mysql.yml
  examples/object_store/user_report/configs/config_s3.yml
  examples/object_store/user_report/upload_to_mysql.sh
Labels: bug, non-breaking

#623 Documentation: Update Using Local LLMs
  docs/source/workflows/using-local-llms.md
  examples/documentation_guides/locally_hosted_llms/nim_config.yml
  examples/documentation_guides/locally_hosted_llms/vllm_config.yml
Labels: doc, non-breaking

#635 Align WebSocket Workflow Output with HTTP Output
  src/nat/front_ends/fastapi/message_handler.py
  src/nat/front_ends/fastapi/message_validator.py
Labels: feature request, non-breaking, ! - Release

#625 Documentation(Providers): Surface LLM; add Embedders and Retrievers
  docs/source/index.md
  docs/source/workflows/embedders.md
  docs/source/workflows/llms/index.md
  docs/source/workflows/llms/using-local-llms.md
  docs/source/workflows/retrievers.md
  docs/source/workflows/workflow-configuration.md
Labels: doc, non-breaking

#615 Enable datasets with custom formats
  ci/scripts/path_checks.py
  docs/source/reference/evaluate.md
  examples/evaluation_and_profiling/simple_calculator_eval/configs
  examples/evaluation_and_profiling/simple_calculator_eval/data
  examples/evaluation_and_profiling/simple_calculator_eval/pyproject.toml
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/__init__.py
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/configs/config-custom-dataset-format.yml
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/configs/config-sizing-calc.yml
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/configs/config-tunable-rag-eval.yml
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/data/simple_calculator_nested.json
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/scripts/__init__.py
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/scripts/custom_dataset_parser.py
  src/nat/data_models/dataset_handler.py
  src/nat/eval/dataset_handler/dataset_handler.py
  src/nat/eval/evaluator/evaluator_model.py
  tests/nat/eval/dataset_handler/test_dataset_handler.py
Labels: improvement, non-breaking

#647 Add UI documentation links and installation instructions
  docs/source/quick-start/launching-ui.md
  examples/front_ends/simple_auth/README.md
Labels: improvement, non-breaking, ! - Release

#632 Consolidate CI pipelines
  .gitlab-ci.yml
  ci/scripts/common.sh
  ci/scripts/github/common.sh
  ci/scripts/gitlab/common.sh
  ci/scripts/gitlab/docs.sh
Labels: improvement, non-breaking

#651 Fix `aiq` compatibility
  pyproject.toml
  src/aiq/__init__.py
  tests/nat/compat/test_compatibility_aliases.py
Labels: bug, non-breaking

#639 Add features `nat workflow create` a versioned dependency and `data` and symlinks folder
  src/nat/cli/commands/workflow/templates/pyproject.toml.j2
  src/nat/cli/commands/workflow/workflow_commands.py
  tests/nat/cli/commands/test_workflow_commands.py
Labels: feature request, non-breaking

#670 Enable `BUILD_NAT_COMPAT`
  .gitlab-ci.yml
Labels: bug, non-breaking

#643 Feature: Azure OpenAI LLM provider and client
  docs/source/workflows/embedders.md
  docs/source/workflows/llms/index.md
  docs/source/workflows/retrievers.md
  packages/nvidia_nat_crewai/src/nat/plugins/crewai/llm.py
  packages/nvidia_nat_langchain/src/nat/plugins/langchain/embedder.py
  packages/nvidia_nat_langchain/src/nat/plugins/langchain/llm.py
  packages/nvidia_nat_llama_index/pyproject.toml
  packages/nvidia_nat_llama_index/src/nat/plugins/llama_index/embedder.py
  packages/nvidia_nat_llama_index/src/nat/plugins/llama_index/llm.py
  packages/nvidia_nat_llama_index/src/nat/plugins/llama_index/register.py
  packages/nvidia_nat_semantic_kernel/src/nat/plugins/semantic_kernel/llm.py
  src/nat/embedder/azure_openai_embedder.py
  src/nat/embedder/openai_embedder.py
  src/nat/embedder/register.py
  src/nat/llm/azure_openai_llm.py
  src/nat/llm/register.py
  tests/nat/compat/test_compatibility_aliases.py
  tests/nat/llm_providers/test_langchain_agents.py
  tests/nat/llm_providers/test_llama_index_agents.py
  uv.lock
Labels: feature request, non-breaking

#674 Add missing compatibility package for `aiqtoolkit-weave`
  packages/compat/aiqtoolkit_weave/pypi.md
  packages/compat/aiqtoolkit_weave/pyproject.toml
Labels: bug, non-breaking

#682 Add a version switcher to the 1.0 documentation builds
  docs/source/conf.py
  docs/source/versions1.json
Labels: doc, non-breaking

#683 Add a version switcher to the 1.1 documentation builds
  docs/source/conf.py
  docs/source/versions1.json
Labels: doc, non-breaking

#686 Fix missing f-string prefixes in error messages
  src/nat/cli/type_registry.py
Labels: bug, non-breaking

#688 [RELEASE] NeMo-Agent-Toolkit v1.2.1
  CHANGELOG.md
  README.md
  ci/release/update-version.sh
  ci/scripts/path_checks.py
  docs/source/conf.py
  docs/source/release-notes.md
  docs/source/versions1.json
  src/nat/meta/pypi.md
Labels: ! - Release

#693 Configure `setuptools_scm` to use the `--first-parent` flag
  examples/HITL/por_to_jiratickets/pyproject.toml
  examples/HITL/simple_calculator_hitl/pyproject.toml
  examples/MCP/simple_calculator_mcp/pyproject.toml
  examples/RAG/simple_rag/pyproject.toml
  examples/advanced_agents/alert_triage_agent/pyproject.toml
  examples/advanced_agents/profiler_agent/pyproject.toml
  examples/custom_functions/automated_description_generation/pyproject.toml
  examples/custom_functions/plot_charts/pyproject.toml
  examples/documentation_guides/workflows/text_file_ingest/pyproject.toml
  examples/evaluation_and_profiling/email_phishing_analyzer/pyproject.toml
  examples/evaluation_and_profiling/simple_calculator_eval/pyproject.toml
  examples/evaluation_and_profiling/simple_web_query_eval/pyproject.toml
  examples/evaluation_and_profiling/swe_bench/pyproject.toml
  examples/frameworks/agno_personal_finance/pyproject.toml
  examples/frameworks/multi_frameworks/pyproject.toml
  examples/frameworks/semantic_kernel_demo/pyproject.toml
  examples/front_ends/simple_auth/pyproject.toml
  examples/front_ends/simple_calculator_custom_routes/pyproject.toml
  examples/getting_started/simple_calculator/pyproject.toml
  examples/getting_started/simple_web_query/pyproject.toml
  examples/notebooks/first_search_agent/pyproject.toml
  examples/notebooks/retail_sales_agent/pyproject.toml
  examples/object_store/user_report/pyproject.toml
  examples/observability/redact_pii/pyproject.toml
  examples/observability/simple_calculator_observability/pyproject.toml
  packages/compat/aiqtoolkit/pyproject.toml
  packages/compat/aiqtoolkit_agno/pyproject.toml
  packages/compat/aiqtoolkit_crewai/pyproject.toml
  packages/compat/aiqtoolkit_langchain/pyproject.toml
  packages/compat/aiqtoolkit_llama_index/pyproject.toml
  packages/compat/aiqtoolkit_mem0ai/pyproject.toml
  packages/compat/aiqtoolkit_semantic_kernel/pyproject.toml
  packages/compat/aiqtoolkit_test/pyproject.toml
  packages/compat/aiqtoolkit_weave/pyproject.toml
  packages/compat/aiqtoolkit_zep_cloud/pyproject.toml
  packages/nvidia_nat_agno/pyproject.toml
  packages/nvidia_nat_all/pyproject.toml
  packages/nvidia_nat_crewai/pyproject.toml
  packages/nvidia_nat_ingestion/pyproject.toml
  packages/nvidia_nat_langchain/pyproject.toml
  packages/nvidia_nat_llama_index/pyproject.toml
  packages/nvidia_nat_mem0ai/pyproject.toml
  packages/nvidia_nat_mysql/pyproject.toml
  packages/nvidia_nat_opentelemetry/pyproject.toml
  packages/nvidia_nat_phoenix/pyproject.toml
  packages/nvidia_nat_profiling/pyproject.toml
  packages/nvidia_nat_ragaai/pyproject.toml
  packages/nvidia_nat_redis/pyproject.toml
  packages/nvidia_nat_s3/pyproject.toml
  packages/nvidia_nat_semantic_kernel/pyproject.toml
  packages/nvidia_nat_test/pyproject.toml
  packages/nvidia_nat_weave/pyproject.toml
  packages/nvidia_nat_zep_cloud/pyproject.toml
  pyproject.toml
  src/nat/cli/commands/workflow/templates/pyproject.toml.j2
Labels: bug, non-breaking

#707 fix(`ModelGatedFieldMixin`): support multiple and indirect inheritance; rename to `GatedFieldMixin`
  docs/source/extend/adding-an-llm-provider.md
  docs/source/extend/gated-fields.md
  docs/source/index.md
  docs/source/workflows/llms/index.md
  src/nat/data_models/gated_field_mixin.py
  src/nat/data_models/model_gated_field_mixin.py
  src/nat/data_models/temperature_mixin.py
  src/nat/data_models/top_p_mixin.py
  tests/nat/data_models/test_gated_field_mixin.py
  tests/nat/data_models/test_model_gated_field_mixin.py
Labels: bug, non-breaking

#710 Add Coderabbit config
  .coderabbit.yaml
Labels: improvement, non-breaking

#714 Configure coderabbit not to apply conflicting labels
  .coderabbit.yaml
Labels: bug, non-breaking

#701 Allow custom post-processing of EvalInput after the workflow is run
  docs/source/reference/evaluate.md
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/configs/config-with-custom-post-process.yml
  examples/evaluation_and_profiling/simple_calculator_eval/src/nat_simple_calculator_eval/scripts/custom_post_process.py
  examples/getting_started/simple_calculator/src/nat_simple_calculator/data/simple_calculator.json
  examples/getting_started/simple_calculator/src/nat_simple_calculator/register.py
  src/nat/data_models/evaluate.py
  src/nat/eval/dataset_handler/dataset_handler.py
  src/nat/eval/evaluate.py
  src/nat/eval/evaluator/evaluator_model.py
  tests/nat/eval/dataset_handler/test_dataset_handler.py
  tests/nat/eval/test_evaluate.py
Labels: improvement, non-breaking

#724 Track agent system prompt in config and add config to skip maintenance check
  examples/advanced_agents/alert_triage_agent/src/nat_alert_triage_agent/maintenance_check.py
  examples/advanced_agents/alert_triage_agent/src/nat_alert_triage_agent/register.py
  examples/advanced_agents/alert_triage_agent/tests/test_alert_triage_agent_workflow.py
  examples/advanced_agents/alert_triage_agent/tests/test_maintenance_check.py
  examples/advanced_agents/alert_triage_agent/tests/test_utils.py
Labels: feature request, non-breaking

#729 Add missing implementation of abstract methods of `ToolTestRunner`
  docs/source/workflows/add-unit-tests-for-tools.md
  packages/nvidia_nat_test/src/nat/test/tool_test_runner.py
  tests/nat/tools/test_tool_test_runner.py
Labels: bug, non-breaking

#730 Improve input normalization of `ReAct` agent
  docs/source/workflows/about/react-agent.md
  src/nat/agent/react_agent/agent.py
  src/nat/agent/react_agent/register.py
  tests/nat/agent/test_react.py
Labels: improvement, non-breaking

#733 fix: Improved model detection/rules for `ThinkingMixin`
  src/nat/data_models/thinking_mixin.py
  tests/nat/data_models/test_thinking_mixin.py
Labels: bug, non-breaking

#736 Add Dynatrace as otel export destination
  ci/vale/styles/config/vocabularies/nat/accept.txt
  docs/source/workflows/observe/observe-workflow-with-otel-collector.md
Labels: doc, non-breaking, external

#738 Add GPU Sizing Launchable Notebook to ``notebooks`` directory
  ci/scripts/path_checks.py
  ci/vale/styles/config/vocabularies/nat/accept.txt
  examples/notebooks/launchables/GPU_Cluster_Sizing_with_NeMo_Agent_Toolkit.ipynb
  examples/notebooks/launchables/README.md
Labels: doc, non-breaking

#718 MCP enhancements: improves server config and adds support for all transport types (stdio, streamable-http)
  ci/scripts/path_checks.py
  docs/source/conf.py
  docs/source/workflows/mcp/mcp-client.md
  docs/source/workflows/mcp/mcp-server.md
  examples/MCP/simple_calculator_mcp/README.md
  examples/MCP/simple_calculator_mcp/configs/config-combined.yml
  examples/MCP/simple_calculator_mcp/configs/config-mcp-date-stdio.yml
  examples/MCP/simple_calculator_mcp/configs/config-mcp-date.yml
  examples/MCP/simple_calculator_mcp/configs/config-mcp-math.yml
  examples/advanced_agents/profiler_agent/pyproject.toml
  examples/evaluation_and_profiling/email_phishing_analyzer/pyproject.toml
  packages/nvidia_nat_phoenix/pyproject.toml
  packages/nvidia_nat_semantic_kernel/pyproject.toml
  pyproject.toml
  src/nat/cli/commands/info/list_mcp.py
  src/nat/cli/commands/start.py
  src/nat/front_ends/mcp/mcp_front_end_config.py
  src/nat/front_ends/mcp/mcp_front_end_plugin.py
  src/nat/tool/mcp/mcp_client_base.py
  src/nat/tool/mcp/mcp_client_impl.py
  src/nat/tool/mcp/mcp_tool.py
  src/nat/tool/register.py
  tests/nat/tools/mcp/test_mcp_client_base.py
  tests/nat/tools/mcp/test_mcp_client_impl.py
  tests/nat/tools/mcp/test_mcp_schema.py
  tests/nat/tools/mcp/test_mcp_tool.py
  uv.lock
Labels: feature request, breaking

#742 Set `StreamHandler` to use `sys.stdout` in `console` registered logging method
  src/nat/observability/register.py
Labels: bug, non-breaking
